#!/usr/bin/env python3
"""Generate independently checked Qwen3 auxiliary linalg kernel examples.

All buffers use the public support.h ABI.  The generated sources are standalone;
this generator does not import the reference repositories or model weights.
"""
from __future__ import annotations

import json
from pathlib import Path


def typ(shape, dtype="f32"):
    return "memref<" + "x".join(map(str, shape)) + "x" + dtype + ">"


def amap(rank, results=None):
    dims = [f"d{i}" for i in range(rank)]
    return "affine_map<(" + ", ".join(dims) + ") -> (" + ", ".join(dims if results is None else results) + ")>"


def generic(inputs, outputs, maps, iters, body):
    args = inputs + outputs
    txt = "    linalg.generic {indexing_maps = [" + ", ".join(maps) + "], iterator_types = [" + ", ".join('"' + i + '"' for i in iters) + "]}\n"
    if inputs:
        txt += "      ins(" + ", ".join(a[0] for a in inputs) + " : " + ", ".join(a[1] for a in inputs) + ")\n"
    txt += "      outs(" + ", ".join(a[0] for a in outputs) + " : " + ", ".join(a[1] for a in outputs) + ") {\n"
    txt += "    ^bb0(" + ", ".join(f"%v{i}: {a[2] if len(a)>2 else 'f32'}" for i, a in enumerate(args)) + "):\n"
    return txt + body + "\n    }\n"


PREAMBLE = '''#include "support.h"
#ifdef HOST_TEST
typedef double oracle_float;
static float oracle_exp(float x) { return (float)exp((double)x); }
static float oracle_sqrt(float x) { return (float)sqrt((double)x); }
static float oracle_sin(float x) { return (float)sin((double)x); }
static float oracle_cos(float x) { return (float)cos((double)x); }
#else
typedef float oracle_float;
static float oracle_exp(float x) { return expf(x); }
static float oracle_sqrt(float x) { return sqrtf(x); }
static float oracle_sin(float x) { return sinf(x); }
static float oracle_cos(float x) { return cosf(x); }
#endif
static void compare(float actual, float expected, float atol, float rtol,
                    int *errors, float *maximum) {
  if (actual == expected) return;
  if (!__builtin_isfinite(actual) || !__builtin_isfinite(expected)) {
    ++*errors; *maximum = __builtin_inff(); return;
  }
  if (!check_close(actual, expected, atol, rtol)) ++*errors;
  float difference = actual - expected;
  if (difference < 0) difference = -difference;
  if (difference > *maximum) *maximum = difference;
}
'''


class Case:
    def __init__(self, name, kind, detail):
        self.name, self.kind, self.detail = name, kind, detail
        self.buffers, self.offset = [], 0
        self.init, self.body, self.verify = [], [], []

    def buffer(self, name, shape, dtype="f32"):
        ctype, size = {"f32": ("float", 4), "i64": ("int64_t", 8),
                       "i8": ("int8_t", 1)}[dtype]
        self.offset = (self.offset + 63) // 64 * 64
        offset = self.offset
        count = 1
        for dim in shape:
            count *= dim
        self.offset += count * size
        self.buffers.append((name, shape, dtype, offset, ctype))
        return ("%" + name, typ(shape, dtype), dtype)

    def emit(self, root):
        directory = root / self.name
        directory.mkdir(parents=True, exist_ok=True)
        function = "kernel_" + self.name
        args = ", ".join("%" + name + ": " + typ(shape, dtype) for name, shape, dtype, _, _ in self.buffers)
        mlir = "// Generated by tools/generate_elementwise.py.\nmodule {\n  func.func @" + function + "(" + args + ") attributes {llvm.emit_c_interface} {\n"
        mlir += "".join(self.body) + "    return\n  }\n}\n"
        prototype = "extern void _mlir_ciface_" + function + "(" + ", ".join("MemRef" + str(len(shape)) + " *" for _, shape, _, _, _ in self.buffers) + ");\n"
        launch = PREAMBLE + prototype + "int launch(void) {\n  int errors = 0; float maximum = 0;\n"
        for name, shape, _, offset, ctype in self.buffers:
            launch += f"  {ctype} *{name} = ({ctype} *)workspace({offset}u);\n"
            launch += f"  MemRef{len(shape)} m_{name} = make_{len(shape)}({name}, " + ", ".join(map(str, shape)) + ");\n"
        launch += "\n".join(self.init) + "\n  _mlir_ciface_" + function + "(" + ", ".join("&m_" + name for name, *_ in self.buffers) + ");\n"
        launch += "\n".join(self.verify) + f'\n  return print_check("{self.name}", errors, maximum);\n}}\n'
        metadata = {"name": self.name, "kind": self.kind, "dtype": "f32", "description": self.detail, "entry": function, "workspace_bytes": self.offset, "buffers": [{"name": n, "shape": s, "dtype": d, "offset": o} for n, s, d, o, _ in self.buffers], "validation": "All output elements versus an independent C oracle; host oracle uses libm double precision."}
        (directory / "kernel.mlir").write_text(mlir)
        (directory / "launch.c").write_text(launch)
        (directory / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
        (directory / "makefile").write_text("include ../common.mk\n")
        return metadata


def pointwise(root, kind, rows, width):
    c = Case(f"{kind}_{rows}x{width}", kind, "SwiGLU activation/product" if width == 3072 else "Residual connection")
    x = c.buffer("x", (rows, width))
    y = c.buffer("y", (rows, width)) if kind != "silu" else None
    out = c.buffer("out", (rows, width))
    count = rows * width
    c.init += [f"  for (int i=0; i<{count}; ++i) {{ x[i] = (float)((i*13)%129-64)*0.125f; out[i] = 9999.0f;" + (" y[i] = (float)((i*7)%31-15)*0.0625f;" if y else "") + " }"]
    if kind == "silu":
        body = "      %one = arith.constant 1.0 : f32\n      %neg = arith.negf %v0 : f32\n      %e = math.exp %neg : f32\n      %den = arith.addf %one, %e : f32\n      %r = arith.divf %v0, %den : f32\n      linalg.yield %r : f32"
        reference = "x[i] / (1.0f + oracle_exp(-x[i]))"
    else:
        body = f"      %r = arith.{'mulf' if kind == 'mul' else 'addf'} %v0, %v1 : f32\n      linalg.yield %r : f32"
        reference = "x[i] " + ("*" if kind == "mul" else "+") + " y[i]"
    inputs = [x, y] if y else [x]
    c.body += [generic(inputs, [out], [amap(2)] * (len(inputs)+1), ["parallel"]*2, body)]
    c.verify += [f"  for (int i=0; i<{count}; ++i) compare(out[i], {reference}, 2e-6f, 3e-5f, &errors, &maximum);"]
    return c.emit(root)


def rmsnorm(root, rows, width):
    c = Case(f"rmsnorm_{rows}x{width}", "rmsnorm", "Qwen3 RMSNorm, including learned per-feature weight and epsilon=1e-6; width128 is per-head Q/K norm")
    x, w, sums, out = c.buffer("x", (rows,width)), c.buffer("weight", (width,)), c.buffer("sums", (rows,)), c.buffer("out", (rows,width))
    c.body += ["    %zero = arith.constant 0.0 : f32\n    %epsilon = arith.constant 1.0e-6 : f32\n" + f"    %divisor = arith.constant {width}.0 : f32\n    linalg.fill ins(%zero : f32) outs(%sums : {typ((rows,))})\n"]
    c.body += [generic([x], [sums], [amap(2),amap(2,["d0"])], ["parallel","reduction"], "      %square = arith.mulf %v0, %v0 : f32\n      %next = arith.addf %v1, %square : f32\n      linalg.yield %next : f32")]
    c.body += [generic([x,w,sums], [out], [amap(2),amap(2,["d1"]),amap(2,["d0"]),amap(2)], ["parallel"]*2, "      %mean = arith.divf %v2, %divisor : f32\n      %variance = arith.addf %mean, %epsilon : f32\n      %rms = math.sqrt %variance : f32\n      %norm = arith.divf %v0, %rms : f32\n      %result = arith.mulf %norm, %v1 : f32\n      linalg.yield %result : f32")]
    c.init += [f"  for (int i=0; i<{rows*width}; ++i) {{ x[i] = (float)((i*7)%37-18)*0.0625f; if(i<{width}) x[i]*=1e-5f; else if(i<{2*width}) x[i]=0; out[i]=9999; }}", f"  for (int i=0; i<{width}; ++i) weight[i]=0.75f+(float)(i%7)*0.0625f;"]
    c.verify += [f"  for (int r=0; r<{rows}; ++r) {{", "    oracle_float sum=0;", f"    for (int k=0; k<{width}; ++k) {{ oracle_float value=x[r*{width}+k]; sum+=value*value; }}", f"    float denominator=oracle_sqrt((float)(sum/{width})+1e-6f);", f"    for (int k=0; k<{width}; ++k) {{ int i=r*{width}+k; compare(out[i], x[i]/denominator*weight[k], 3e-6f, 5e-5f, &errors, &maximum); }}", "  }"]
    return c.emit(root)


def rope(root, sequence, heads):
    c = Case(f"rope_{sequence}x{heads}x128", "rope", "Split-half Qwen3 RoPE; sin/cos are precomputed inputs, theta=1000000 and nonzero absolute position offset7")
    shape = (sequence,heads,2,64)
    x, cosine, sine, out = c.buffer("x",shape), c.buffer("cosine",(sequence,64)), c.buffer("sine",(sequence,64)), c.buffer("out",shape)
    c.body += ["    %c0 = arith.constant 0 : index\n    %c1 = arith.constant 1 : index\n"]
    body = f"""      %s = linalg.index 0 : index
      %h = linalg.index 1 : index
      %half = linalg.index 2 : index
      %k = linalg.index 3 : index
      %other = arith.subi %c1, %half : index
      %partner = memref.load %x[%s, %h, %other, %k] : {typ(shape)}
      %negative = arith.negf %partner : f32
      %first = arith.cmpi eq, %half, %c0 : index
      %rotated = arith.select %first, %negative, %partner : f32
      %a = arith.mulf %v0, %v1 : f32
      %b = arith.mulf %rotated, %v2 : f32
      %r = arith.addf %a, %b : f32
      linalg.yield %r : f32"""
    c.body += [generic([x,cosine,sine], [out], [amap(4),amap(4,["d0","d3"]),amap(4,["d0","d3"]),amap(4)], ["parallel"]*4, body)]
    c.init += [f"  for (int i=0; i<{sequence*heads*128}; ++i) {{ x[i]=(float)((i*5)%53-26)*0.03125f; out[i]=9999; }}", f"  for (int s=0; s<{sequence}; ++s) for (int k=0; k<64; ++k) {{", "    float frequency=oracle_exp(-13.815510557964274f*(float)k/64.0f);", "    float angle=(float)(s+7)*frequency; cosine[s*64+k]=oracle_cos(angle); sine[s*64+k]=oracle_sin(angle);", "  }"]
    c.verify += [f"  for (int s=0; s<{sequence}; ++s) for (int h=0; h<{heads}; ++h) for (int k=0; k<64; ++k) {{", f"    int first=(s*{heads}+h)*128+k, second=first+64;", "    float a=x[first]*cosine[s*64+k]-x[second]*sine[s*64+k];", "    float b=x[second]*cosine[s*64+k]+x[first]*sine[s*64+k];", "    compare(out[first],a,2e-6f,3e-5f,&errors,&maximum); compare(out[second],b,2e-6f,3e-5f,&errors,&maximum);", "  }"]
    return c.emit(root)


def softmax(root, sequence, total):
    shape=(16,sequence,total)
    c=Case(f"softmax_16x{sequence}x{total}", "softmax", "Stable attention softmax: subtract row maximum, exponentiate and normalize along cache length")
    x, maxima, sums, out=c.buffer("x",shape),c.buffer("maxima",shape[:2]),c.buffer("sums",shape[:2]),c.buffer("out",shape)
    c.body += ["    %zero = arith.constant 0.0 : f32\n    %negative_inf = arith.constant 0xFF800000 : f32\n" + f"    linalg.fill ins(%negative_inf : f32) outs(%maxima : {typ(shape[:2])})\n    linalg.fill ins(%zero : f32) outs(%sums : {typ(shape[:2])})\n"]
    c.body += [generic([x],[maxima],[amap(3),amap(3,["d0","d1"])],["parallel","parallel","reduction"],"      %m = arith.maximumf %v0, %v1 : f32\n      linalg.yield %m : f32")]
    c.body += [generic([x,maxima],[sums],[amap(3),amap(3,["d0","d1"]),amap(3,["d0","d1"])],["parallel","parallel","reduction"],"      %d = arith.subf %v0, %v1 : f32\n      %e = math.exp %d : f32\n      %sum = arith.addf %v2, %e : f32\n      linalg.yield %sum : f32")]
    c.body += [generic([x,maxima,sums],[out],[amap(3),amap(3,["d0","d1"]),amap(3,["d0","d1"]),amap(3)],["parallel"]*3,"      %d = arith.subf %v0, %v1 : f32\n      %e = math.exp %d : f32\n      %r = arith.divf %e, %v2 : f32\n      linalg.yield %r : f32")]
    c.init += [f"  for (int row=0; row<{16*sequence}; ++row) for (int k=0; k<{total}; ++k) {{", f"    int i=row*{total}+k; x[i]=80.0f+(float)((i*7)%53-26)*0.25f; out[i]=9999;", (f"    if (k>row%{sequence}) x[i]=-__builtin_inff();" if sequence>1 else "    if (k==5) x[i]=-__builtin_inff();"), "  }"]
    c.verify += [f"  for (int row=0; row<{16*sequence}; ++row) {{", "    float maximum_input=-__builtin_inff(); oracle_float sum=0;", f"    for (int k=0; k<{total}; ++k) if(x[row*{total}+k]>maximum_input) maximum_input=x[row*{total}+k];", f"    for (int k=0; k<{total}; ++k) sum+=oracle_exp(x[row*{total}+k]-maximum_input);", "    oracle_float output_sum=0;", f"    for (int k=0; k<{total}; ++k) {{ int i=row*{total}+k; float expected=(float)(oracle_exp(x[i]-maximum_input)/sum); compare(out[i],expected,2e-6f,5e-5f,&errors,&maximum); output_sum+=out[i]; }}", "    compare((float)output_sum,1.0f,3e-6f,3e-6f,&errors,&maximum);", "  }"]
    return c.emit(root)


def causal_mask(root, sequence, total):
    shape=(16,sequence,total)
    past=total-sequence
    c=Case(f"attention_scale_mask_16x{sequence}x{total}", "attention_scale_mask", "Scale QK by 1/sqrt(128), then apply causal mask with absolute query position past+s")
    x,out=c.buffer("x",shape),c.buffer("out",shape)
    c.body += [f"    %past = arith.constant {past} : index\n    %scale = arith.constant 0.08838834764831845 : f32\n    %negative_inf = arith.constant 0xFF800000 : f32\n"]
    c.body += [generic([x],[out],[amap(3)]*2,["parallel"]*3,"      %s = linalg.index 1 : index\n      %t = linalg.index 2 : index\n      %position = arith.addi %s, %past : index\n      %valid = arith.cmpi ule, %t, %position : index\n      %scaled = arith.mulf %v0, %scale : f32\n      %r = arith.select %valid, %scaled, %negative_inf : f32\n      linalg.yield %r : f32")]
    c.init += [f"  for(int i=0; i<{16*sequence*total}; ++i) {{ x[i]=(float)((i*11)%61-30)*0.25f; out[i]=9999; }}"]
    c.verify += [f"  for (int h=0; h<16; ++h) for(int s=0; s<{sequence}; ++s) for(int t=0; t<{total}; ++t) {{", f"    int i=(h*{sequence}+s)*{total}+t; float expected=t<=s+{past}?x[i]/oracle_sqrt(128.0f):-__builtin_inff();", "    compare(out[i],expected,1e-6f,2e-6f,&errors,&maximum);", "  }"]
    return c.emit(root)


def embedding(root, sequence):
    c=Case(f"embedding_{sequence}x1024", "embedding", "Gather full-vocabulary embedding rows [151936,1024]; tied lm_head shares this weight semantically")
    # Put the dense vocabulary last so all other buffers have compact offsets.
    ids,out,weight=c.buffer("ids",(sequence,),"i64"),c.buffer("out",(sequence,1024)),c.buffer("weight",(151936,1024))
    c.body += [generic([ids],[out],[amap(2,["d0"]),amap(2)],["parallel"]*2,f"      %feature = linalg.index 1 : index\n      %token = arith.index_cast %v0 : i64 to index\n      %value = memref.load %weight[%token, %feature] : {typ((151936,1024))}\n      linalg.yield %value : f32")]
    c.init += [f"  for (int s=0; s<{sequence}; ++s) {{", "    ids[s]=(s%4==0)?151935:((s*997+3)%151936);", "    for(int k=0;k<1024;++k) { weight[ids[s]*1024+k]=(float)((ids[s]+k*3)%97-48)*0.03125f; out[s*1024+k]=9999; }", "  }"]
    c.verify += [f"  for(int s=0;s<{sequence};++s) for(int k=0;k<1024;++k) {{", "    float expected=(float)((ids[s]+k*3)%97-48)*0.03125f; compare(out[s*1024+k],expected,0,0,&errors,&maximum);", "  }"]
    return c.emit(root)


def embedding_w8a8(root, sequence):
    """Gather int8 embedding rows and scale them back to f32.

    The W8A8 deployment quantises the tied embedding/lm_head matrix, so the
    gather cannot use the f32 kernel: it reads int8 rows and multiplies each row
    by that token's stored scale, matching tools/quant_reference.py exactly.
    Keeping it f32 costs 622 MB for the full model, which does not fit.
    """
    c=Case(f"embedding_w8a8_{sequence}x1024", "embedding_w8a8", "Gather int8 embedding rows and rescale to f32 by the per-token scale")
    ids,out,weight,scale=(c.buffer("ids",(sequence,),"i64"),c.buffer("out",(sequence,1024)),
                          c.buffer("weight",(151936,1024),"i8"),c.buffer("scale",(151936,)))
    c.body += [generic([ids],[out],[amap(2,["d0"]),amap(2)],["parallel"]*2,
        f"      %feature = linalg.index 1 : index\n      %token = arith.index_cast %v0 : i64 to index\n      %q = memref.load %weight[%token, %feature] : {typ((151936,1024),'i8')}\n      %qf = arith.sitofp %q : i8 to f32\n      %s = memref.load %scale[%token] : {typ((151936,))}\n      %value = arith.mulf %qf, %s : f32\n      linalg.yield %value : f32")]
    c.init += [f"  for (int s=0; s<{sequence}; ++s) {{", "    ids[s]=(s%4==0)?151935:((s*997+3)%151936);", "    scale[ids[s]]=(float)((ids[s]%13)+1)*0.0078125f;", "    for(int k=0;k<1024;++k) { weight[ids[s]*1024+k]=(int8_t)(((ids[s]+k*3)%255)-127); out[s*1024+k]=9999; }", "  }"]
    c.verify += [f"  for(int s=0;s<{sequence};++s) for(int k=0;k<1024;++k) {{", "    float expected=(float)(int8_t)(((ids[s]+k*3)%255)-127)*scale[ids[s]]; compare(out[s*1024+k],expected,0,0,&errors,&maximum);", "  }"]
    return c.emit(root)


def kv_cache(root, sequence, past):
    capacity=32
    c=Case(f"kv_cache_update_{sequence}x8x128", "kv_cache_update", "Append projected/rotated K or projected V from [S,8,128] into [8,32,128] cache; preserve untouched entries")
    x,cache=c.buffer("x",(sequence,8,128)),c.buffer("cache",(8,capacity,128))
    c.body += [f"    %past = arith.constant {past} : index\n"]
    # Iteration is over x; cache is a captured destination because shifted writes
    # are not representable as a full static linalg output indexing permutation.
    c.body += [generic([], [x], [amap(3)], ["parallel"]*3, f"      %s = linalg.index 0 : index\n      %h = linalg.index 1 : index\n      %d = linalg.index 2 : index\n      %position = arith.addi %s, %past : index\n      memref.store %v0, %cache[%h, %position, %d] : {typ((8,capacity,128))}\n      linalg.yield %v0 : f32")]
    c.init += [f"  for(int i=0;i<{sequence*8*128};++i) x[i]=(float)((i*17)%101-50)*0.0625f;", f"  for(int i=0;i<{8*capacity*128};++i) cache[i]=(float)((i*3)%47-23)*0.03125f;"]
    c.verify += [f"  for(int h=0;h<8;++h) for(int t=0;t<{capacity};++t) for(int d=0;d<128;++d) {{", f"    int i=(h*{capacity}+t)*128+d; float expected=(float)((i*3)%47-23)*0.03125f;", f"    if(t>={past} && t<{past+sequence}) expected=x[((t-{past})*8+h)*128+d];", "    compare(cache[i],expected,0,0,&errors,&maximum);", "  }"]
    return c.emit(root)


def gqa_layout(root, total):
    c=Case(f"gqa_repeat_8x{total}x128_to_16x{total}x128", "gqa_repeat", "GQA repeat_kv: query head h reads KV head floor(h/2), retaining token and head_dim axes")
    x,out=c.buffer("x",(8,total,128)),c.buffer("out",(16,total,128))
    c.body += ["    %c2 = arith.constant 2 : index\n"]
    c.body += [generic([], [out], [amap(3)], ["parallel"]*3, f"      %h = linalg.index 0 : index\n      %t = linalg.index 1 : index\n      %d = linalg.index 2 : index\n      %kv_head = arith.divui %h, %c2 : index\n      %value = memref.load %x[%kv_head, %t, %d] : {typ((8,total,128))}\n      linalg.yield %value : f32")]
    c.init += [f"  for(int i=0;i<{8*total*128};++i) x[i]=(float)((i*11)%127-63)*0.03125f;", f"  for(int i=0;i<{16*total*128};++i) out[i]=9999;"]
    c.verify += [f"  for(int h=0;h<16;++h) for(int t=0;t<{total};++t) for(int d=0;d<128;++d) {{", f"    compare(out[(h*{total}+t)*128+d],x[((h/2)*{total}+t)*128+d],0,0,&errors,&maximum);", "  }"]
    return c.emit(root)


def transpose(root, name, shape, permutation, detail):
    output_shape=tuple(shape[i] for i in permutation)
    c=Case(name, "layout_transpose", detail)
    x,out=c.buffer("x",shape),c.buffer("out",output_shape)
    inverse=[permutation.index(i) for i in range(3)]
    c.body += [generic([x],[out],[amap(3,[f"d{i}" for i in inverse]),amap(3)],["parallel"]*3,"      linalg.yield %v0 : f32")]
    count=shape[0]*shape[1]*shape[2]
    c.init += [f"  for(int i=0;i<{count};++i) {{ x[i]=(float)((i*19)%4093-2046)*0.015625f; out[i]=9999; }}"]
    c.verify += [f"  for(int a=0;a<{shape[0]};++a) for(int b=0;b<{shape[1]};++b) for(int d=0;d<{shape[2]};++d) {{", "    int index[3]={a,b,d};", f"    int input=(a*{shape[1]}+b)*{shape[2]}+d;", f"    int output=(index[{permutation[0]}]*{output_shape[1]}+index[{permutation[1]}])*{output_shape[2]}+index[{permutation[2]}];", "    compare(out[output],x[input],0,0,&errors,&maximum);", "  }"]
    return c.emit(root)


def generate(root: Path):
    root=Path(root)
    cases=[]
    for sequence in (16,1):
        cases.append(embedding(root,sequence))
        cases.append(embedding_w8a8(root,sequence))
        for kind,width in (("silu",3072),("mul",3072),("add",1024)):
            cases.append(pointwise(root,kind,sequence,width))
        for heads in (16,8):
            cases.append(rope(root,sequence,heads))
        cases.append(kv_cache(root,sequence,0 if sequence==16 else 16))
    for rows,width in ((16,1024),(1,1024),(256,128),(128,128),(16,128),(8,128)):
        cases.append(rmsnorm(root,rows,width))
    for sequence,total in ((16,16),(1,17)):
        cases.append(softmax(root,sequence,total))
        cases.append(causal_mask(root,sequence,total))
        cases.append(gqa_layout(root,total))
        cases.append(transpose(root,f"layout_q_{sequence}x16x128",(sequence,16,128),(1,0,2),"Transpose Q from token-major projection view [S,16,128] to [16,S,128]"))
        cases.append(transpose(root,f"layout_k_16x{total}x128",(16,total,128),(0,2,1),"Transpose expanded K [16,T,128] into [16,128,T] for QK batch_matmul"))
        cases.append(transpose(root,f"layout_context_16x{sequence}x128",(16,sequence,128),(1,0,2),"Transpose attention context [16,S,128] to [S,16,128], then view as [S,2048] for o_proj"))
    # The model's attention runs over the full 512-slot cache, and QK is
    # `A[M,K] @ B[K,N]` in the attention_dot kernel -- so K has to be handed over
    # already transposed to [16,128,512]. The 16- and 17-slot variants above are
    # for the small cases; without this one the model's attention cannot be
    # replaced at all.
    # The KV write kernel indexes X as [S, 8, 128] (token-major) while the graph
    # carries the projected K/V as [1, 8, S, 128] (head-major), so the value needs
    # the same dim-1/dim-2 swap layout_context does -- but with 8 heads, not 16.
    for sequence in (16, 1):
        cases.append(transpose(root,f"layout_context_8x{sequence}x128",(8,sequence,128),(1,0,2),
                               "Transpose head-major projected K/V [8,S,128] to token-major [S,8,128] for the cache write"))
    cases.append(transpose(root,"layout_k_16x512x128",(16,512,128),(0,2,1),
                           "Transpose the 512-slot expanded K [16,512,128] into [16,128,512] for the QK batch_matmul"))
    return cases


if __name__ == "__main__":
    result=generate(Path(__file__).resolve().parents[1])
    print(f"Generated {len(result)} Qwen3 auxiliary operator cases")
