name: checkout_llvm
description: Prepare the LLVM submodule

inputs:
  llvm-src:
    description: Path to the llvm-project checkout.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout LLVM
      id: checkout-llvm
      shell: bash
      run: |
        LLVM_SRC="${{ inputs.llvm-src }}"

        LLVM_COMMIT=$(git ls-tree HEAD llvm | awk '{print $3}')
        PATCH_HASH=$(shasum -a 256 "$GITHUB_WORKSPACE/riscv-jitlink.patch" | awk '{print $1}')
        LLVM_HASH="${LLVM_COMMIT}-${PATCH_HASH:0:12}"

        if [ ! -d "$LLVM_SRC" ]; then
          git clone https://community-ci.openruyi.cn/toolchain/llvm-project.git $LLVM_SRC
        fi

        git submodule sync --recursive
        git -C $LLVM_SRC fetch --all
        git -C $LLVM_SRC checkout -f $LLVM_COMMIT
        git -C $LLVM_SRC reset --hard HEAD
        git -C $LLVM_SRC clean -fdx

        git -C $LLVM_SRC apply $GITHUB_WORKSPACE/riscv-jitlink.patch
