//===- ModelSession.h - Runtime session for DeepSeek R1 (generated)
//----------===//
//
// Auto-generated by tools/buddy-codegen/gen_session.py — DO NOT EDIT.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// ModelSession owns all persistent state for one inference session:
//   - KV cache buffers (one MemRef per layer), managed via BufferPool
//   - Logits output buffer
//   - Decode position counter
//   - Loaded model .so handle (dlopen/dlclose lifecycle)
//   - Weight tensors (loaded via loadWeights() from paths in the manifest or
//   CLI)
//
// Host code calls loadWeights(), then prefill() / decode().
//
//===----------------------------------------------------------------------===//

#ifndef BUDDY_RUNTIME_MODELS_MODELSESSION_H
#define BUDDY_RUNTIME_MODELS_MODELSESSION_H

#include "buddy/runtime/core/BufferPool.h"
#include "buddy/runtime/core/ModelManifest.h"
#include "buddy/runtime/llm/LLMSession.h"

#include "buddy/Core/Container.h"
#include "buddy/LLM/TextContainer.h"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#ifndef BUDDY_DSR1_HEAD_NUM
#define BUDDY_DSR1_HEAD_NUM 2
#endif
#ifndef BUDDY_DSR1_MAX_TOKEN_LEN
#define BUDDY_DSR1_MAX_TOKEN_LEN 1024
#endif
#ifndef BUDDY_DSR1_HIDDEN_SIZE
#define BUDDY_DSR1_HIDDEN_SIZE 128
#endif
#ifndef BUDDY_DSR1_VOCAB_SIZE
#define BUDDY_DSR1_VOCAB_SIZE 151936
#endif
#ifndef BUDDY_DSR1_KV_LAYERS
#define BUDDY_DSR1_KV_LAYERS 56
#endif
#ifndef BUDDY_DSR1_PARAMS_SIZE_PARAMS
#define BUDDY_DSR1_PARAMS_SIZE_PARAMS 1777088064LL
#endif
#ifndef BUDDY_DSR1_PARAMS_SIZE
#define BUDDY_DSR1_PARAMS_SIZE 1777088064LL
#endif

namespace buddy {
namespace runtime {

//===----------------------------------------------------------------------===//
// ModelSession
//===----------------------------------------------------------------------===//

/// Encapsulates one inference session for this model variant (shapes and
/// weight layout come from the generated macros above).
///
/// Typical workflow: loadWeights() → prefill() → decode() in a loop.

class ModelSession : public LLMSession {
public:
  struct Config {
    /// Path to the runtime-loadable model shared library (dlopen).
    std::string modelSoPath;
    int headNum = BUDDY_DSR1_HEAD_NUM;
    int maxTokenLen = BUDDY_DSR1_MAX_TOKEN_LEN;
    int hiddenSize = BUDDY_DSR1_HIDDEN_SIZE;
    int vocabSize = BUDDY_DSR1_VOCAB_SIZE;
    int kvLayers = BUDDY_DSR1_KV_LAYERS;
  };

  /// Allocates KV cache, then dlopen + dlsym. Throws on failure.
  static std::unique_ptr<ModelSession> create(const Config &cfg);
  /// Build from a packed .rax manifest (fills resolvedManifest with paths).
  static std::unique_ptr<ModelSession>
  createFromRax(const std::string &raxPath, ModelManifest &resolvedManifest);

  ~ModelSession() override;
  // Non-copyable
  ModelSession(const ModelSession &) = delete;
  ModelSession &operator=(const ModelSession &) = delete;

  /// Load all weight blobs from disk (order matches the compiled manifest).
  void loadWeights(const std::vector<std::string> &weightPaths) override;
  /// Run prefill over the prompt tokens (weights must be loaded first).
  void prefill(Text<size_t, 2> &tokens) override;
  /// One decode step for a single token id.
  void decode(int tokenId) override;

  void resetPosition() override;
  /// KV overflow: discard tokens and fix RoPE on surviving keys.
  bool handleKVCacheOverflow(int keepTokenNum,
                             float ropeTheta = 10000.0f) override;
  int position() const override { return position_; }
  /// Logits for one position; non-f32 logits may be converted to float.
  const float *logitsData(int tokenOffset = 0) const override;
  int vocabSize() const override { return cfg_.vocabSize; }
  std::string loadedSoPath() const;
  const BufferPool &bufferPool() const { return pool_; }

private:
  explicit ModelSession(const Config &cfg);
  void allocateKVCache();

  Config cfg_;
  BufferPool pool_;
  int position_ = 0;

  // Pimpl: KVCacheABI, dlopen handle, and function pointers.
  struct Impl;
  std::unique_ptr<Impl> impl_;

  // Decode step inputs (reused every call).
  std::unique_ptr<MemRef<long long, 2>> decodeTokenInput_;
  std::unique_ptr<MemRef<long long, 1>> cachePosition_;

  std::unique_ptr<MemRef<float, 1>> params_;
};

} // namespace runtime
} // namespace buddy

#endif // BUDDY_RUNTIME_MODELS_MODELSESSION_H
