// Auto-generated by tools/buddy-codegen/gen_session.py — DO NOT EDIT.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef BUDDY_RUNTIME_MODELS_MODELSESSION_H
#define BUDDY_RUNTIME_MODELS_MODELSESSION_H

#include "buddy/runtime/core/BufferPool.h"
#include "buddy/runtime/core/ModelManifest.h"
#include "buddy/runtime/llm/LLMSession.h"

#include "buddy/Core/Container.h"
#include "buddy/LLM/TextContainer.h"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#ifndef BUDDY_DSR1_HEAD_NUM
#define BUDDY_DSR1_HEAD_NUM 2
#endif
#ifndef BUDDY_DSR1_MAX_TOKEN_LEN
#define BUDDY_DSR1_MAX_TOKEN_LEN 1024
#endif
#ifndef BUDDY_DSR1_HIDDEN_SIZE
#define BUDDY_DSR1_HIDDEN_SIZE 128
#endif
#ifndef BUDDY_DSR1_VOCAB_SIZE
#define BUDDY_DSR1_VOCAB_SIZE 151936
#endif
#ifndef BUDDY_DSR1_KV_LAYERS
#define BUDDY_DSR1_KV_LAYERS 56
#endif
#ifndef BUDDY_DSR1_PARAMS_SIZE_F16_PARAMS
#define BUDDY_DSR1_PARAMS_SIZE_F16_PARAMS 322338752
#endif
#ifndef BUDDY_DSR1_PARAMS_SIZE_I8_PARAMS
#define BUDDY_DSR1_PARAMS_SIZE_I8_PARAMS 1455489024LL
#endif

namespace buddy {
namespace runtime {

class ModelSession : public LLMSession {
public:
  struct Config {
    std::string modelSoPath;
    int headNum = BUDDY_DSR1_HEAD_NUM;
    int maxTokenLen = BUDDY_DSR1_MAX_TOKEN_LEN;
    int hiddenSize = BUDDY_DSR1_HIDDEN_SIZE;
    int vocabSize = BUDDY_DSR1_VOCAB_SIZE;
    int kvLayers = BUDDY_DSR1_KV_LAYERS;
  };

  static std::unique_ptr<ModelSession> create(const Config &cfg);
  static std::unique_ptr<ModelSession>
  createFromRax(const std::string &raxPath, ModelManifest &resolvedManifest);

  ~ModelSession() override;
  ModelSession(const ModelSession &) = delete;
  ModelSession &operator=(const ModelSession &) = delete;

  void loadWeights(const std::vector<std::string> &weightPaths) override;
  void prefill(Text<size_t, 2> &tokens) override;
  void decode(int tokenId) override;

  void resetPosition() override;
  bool handleKVCacheOverflow(int keepTokenNum,
                             float ropeTheta = 10000.0f) override;
  int position() const override { return position_; }
  const float *logitsData(int tokenOffset = 0) const override;
  int vocabSize() const override { return cfg_.vocabSize; }
  std::string loadedSoPath() const;
  const BufferPool &bufferPool() const { return pool_; }

private:
  explicit ModelSession(const Config &cfg);
  void allocateKVCache();

  Config cfg_;
  BufferPool pool_;
  int position_ = 0;

  struct Impl;
  std::unique_ptr<Impl> impl_;

  std::unique_ptr<MemRef<long long, 2>> decodeTokenInput_;
  std::unique_ptr<MemRef<long long, 1>> cachePosition_;

  std::unique_ptr<MemRef<uint16_t, 1>> f16_params_;
  std::unique_ptr<MemRef<int8_t, 1>> i8_params_;
  mutable std::vector<float> logitsFloat_;
};

} // namespace runtime
} // namespace buddy

#endif // BUDDY_RUNTIME_MODELS_MODELSESSION_H
