//===- launch.c - Board/host launcher for add_1x1024 ----------------------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Fills workspace, calls the MLIR C iface, and checks against a C oracle.
// Linked for both HOST_TEST (make check) and the NR board image.
//
// On the board, RA CRT calls launch() after BSS clear. Return 0 is PASS;
// non-zero (or a trap) becomes FAIL on the NH/RA mailbox and UART.
//
//===----------------------------------------------------------------------===//

#include "support.h"

// Host oracle helpers use libm (double). Board builds use freestanding nr_math.
// add_1x1024 itself only needs x[i]+y[i]; the oracle_* wrappers stay so other
// operators can share the same launch skeleton.
#ifdef HOST_TEST
typedef double oracle_float;
static float oracle_exp(float x) { return (float)exp((double)x); }
static float oracle_sqrt(float x) { return (float)sqrt((double)x); }
static float oracle_sin(float x) { return (float)sin((double)x); }
static float oracle_cos(float x) { return (float)cos((double)x); }
#else
typedef float oracle_float;
static float oracle_exp(float x) { return expf(x); }
static float oracle_sqrt(float x) { return sqrtf(x); }
static float oracle_sin(float x) { return sinf(x); }
static float oracle_cos(float x) { return cosf(x); }
#endif

// Count mismatches and track the max absolute error for print_check().
static void compare(float actual, float expected, float atol, float rtol,
                    int *errors, float *maximum) {
  if (actual == expected)
    return;
  // Non-finite values: only identical infinities would have matched above.
  if (!__builtin_isfinite(actual) || !__builtin_isfinite(expected)) {
    ++*errors;
    *maximum = __builtin_inff();
    return;
  }
  if (!check_close(actual, expected, atol, rtol))
    ++*errors;
  float difference = actual - expected;
  if (difference < 0)
    difference = -difference;
  if (difference > *maximum)
    *maximum = difference;
}

// Generated by llvm.emit_c_interface on kernel_add_1x1024.
extern void _mlir_ciface_kernel_add_1x1024(MemRef2 *, MemRef2 *, MemRef2 *);

int launch(void) {
  int errors = 0;
  float maximum = 0;

  // Three 1x1024 f32 buffers in the NOLOAD workspace (see metadata.json).
  // Offsets: x@0, y@4096, out@8192 (1024 * sizeof(float) each).
  float *x = (float *)workspace(0u);
  MemRef2 m_x = make_2(x, 1, 1024);
  float *y = (float *)workspace(4096u);
  MemRef2 m_y = make_2(y, 1, 1024);
  float *out = (float *)workspace(8192u);
  MemRef2 m_out = make_2(out, 1, 1024);

  // Deterministic inputs. Seed out with a sentinel so an unwritten result
  // cannot accidentally match the oracle.
  for (int i = 0; i < 1024; ++i) {
    x[i] = (float)((i * 13) % 129 - 64) * 0.125f;
    out[i] = 9999.0f;
    y[i] = (float)((i * 7) % 31 - 15) * 0.0625f;
  }

  _mlir_ciface_kernel_add_1x1024(&m_x, &m_y, &m_out);

  // Independent C oracle: elementwise add, not the MLIR kernel path.
  for (int i = 0; i < 1024; ++i)
    compare(out[i], x[i] + y[i], 2e-6f, 3e-5f, &errors, &maximum);

  // Emits "verify add_1x1024: PASS/FAIL ..." on UART (board) or stdout (host).
  return print_check("add_1x1024", errors, maximum);
}
