/* Generated by triton/cases.py; independent C hardswish oracle. */
#include "support.h"
#define COUNT 47040
#define BLOCK 128
#ifndef HOST_TEST
static float x_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define out_storage NULL
#endif
static float reference[COUNT] WORKSPACE;
extern void run_hardswish(float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int i, int trial) {
  /* Every case and every tail contains -3/+3 and their FP32 neighbors,
   * signed zero, extreme magnitudes, infinities and quiet NaNs. */
  static const uint32_t edges[16] = {
    0xff800000u, 0xff7fffffu, 0xc0400001u, 0xc0400000u,
    0xc03fffffu, 0xbf800000u, 0x80000000u, 0x00000000u,
    0x3f800000u, 0x403fffffu, 0x40400000u, 0x40400001u,
    0x7f7fffffu, 0x7f800000u, 0x7fc00001u, 0xffc00001u
  };
  if (i < 16 || i >= COUNT - 16) {
    union { uint32_t u; float f; } bits = {edges[(i + trial * 5) % 16]};
    return bits.f;
  }
  return (float)((i * 173 + trial * 131) % 2049 - 1024) * 0.0078125f;
}

int launch(void) {
  GuardedBuffer x = {0}, out = {0};
  if (buffer_init(&x, COUNT, x_storage)) return report_check("hardswish_count47040", 1, 0);
  if (buffer_init(&out, COUNT, out_storage)) {
    buffer_free(&x); return report_check("hardswish_count47040", 1, 0);
  }
  unsigned errors = 0;
  float maximum = 0;
  for (int trial = 0; trial < 3; ++trial) {
    unsigned regions[5] = {0};
    for (int i = 0; i < COUNT; ++i) {
      float value = x_value(i, trial);
      x.data[i] = value;
      out.data[i] = -9999.0f;
      regions[0] += value < -3.0f;
      regions[1] += value == -3.0f;
      regions[2] += value > -3.0f && value < 3.0f;
      regions[3] += value == 3.0f;
      regions[4] += value > 3.0f;
    }
    for (int region = 0; region < 5; ++region) errors += regions[region] == 0;
    /* Independent scalar C reference before calling the compiled kernel.
     * Preserve FP32 multiply before division, rather than x*hardsigmoid(x).
     * Comparisons preserve NaN. -Inf*0 is NaN; +FLT_MAX*6 overflows to +Inf. */
    for (int i = 0; i < COUNT; ++i) {
      float value = x.data[i] + 3.0f;
      if (value < 0.0f) value = 0.0f;
      if (value > 6.0f) value = 6.0f;
      float product = x.data[i] * value;
      reference[i] = product / 6.0f;
    }
    run_hardswish(x.data, out.data);
    for (int i = 0; i < COUNT; ++i) {
      if (__builtin_isnan(reference[i])) {
        errors += !__builtin_isnan(out.data[i]);
      } else if (__builtin_isinf(reference[i])) {
        errors += out.data[i] != reference[i];
      } else if (!__builtin_isfinite(out.data[i])) {
        ++errors; maximum = __builtin_inff();
      } else {
        /* Exact numerical equality accepts either zero sign. */
        errors += out.data[i] != reference[i];
        float difference = out.data[i] - reference[i];
        if (difference < 0) difference = -difference;
        if (difference > maximum) maximum = difference;
      }
      errors += float_bits(x.data[i]) != float_bits(x_value(i, trial));
    }
    errors += buffer_check(&x) + buffer_check(&out);
  }
  buffer_free(&x); buffer_free(&out);
  return report_check("hardswish_count47040", errors, maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
