/* Generated by cases.py; independent NCHW 1x1 Conv2D double oracle. */
#include "support.h"
#ifdef HOST_TEST
#include <stdio.h>
#endif
#define CIN 144
#define COUT 576
#define H 1
#define W 1
#define INPUT_COUNT (CIN * H * W)
#define WEIGHT_COUNT (COUT * CIN)
#define OUTPUT_COUNT (COUT * H * W)
#define TRIALS 9
#ifndef HOST_TEST
static float x_storage[INPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float weight_storage[WEIGHT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float bias_storage[COUT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[OUTPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define weight_storage NULL
#define bias_storage NULL
#define out_storage NULL
#endif
extern void run_pointwise_conv2d(float *, float *, float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int ic, int h, int w, int trial) {
  if (trial == 0) return ic % 2 ? -0.0f : 0.0f;
  if (trial == 1) return (float)(ic + 1) * 0.006f + h * 0.031f - w * 0.019f;
  if (trial == 2) return ic == 0 ? 0.25f + h * 0.01f + w * 0.03f : 0.0f;
  if (trial == 3) return ic == CIN - 1 ? -0.5f + h * 0.02f - w * 0.07f : 0.0f;
  if (trial == 5) {
    float scale = (float)(ic + 1) * 0.03125f;
    if (h == 0 && w == 0) return scale;
    if (h == 0 && w == W - 1) return -2 * scale;
    if (h == H - 1 && w == 0) return 3 * scale;
    if (h == H - 1 && w == W - 1) return -4 * scale;
    return 0.0f;
  }
  if (trial == 6) return (ic % 2 ? -0.25f : 0.25f) + (float)((h + w) % 7) * 0.0001f;
  return (float)((ic * 17 + h * 37 + w * 13 + trial * 11) % 251 - 125) * 0.009f;
}

static float weight_value(int oc, int ic, int trial) {
  if (trial == 4) return ic == (oc * 7 + 3) % CIN ? (float)(oc % 17 - 8) * 0.03125f : 0.0f;
  if (trial == 6) return 0.75f + (float)((oc * 3 + ic * 7) % 13) * 0.0001f;
  if (trial == 8 && oc != COUT - 1) return 0.0f;
  return (float)((oc * 31 + ic * 19 + trial * 3) % 97 - 48) * 0.013f;
}

static float bias_value(int oc, int trial) {
  if (trial == 8) return oc == COUT - 1 ? -0.25f : 0.0f;
  return (float)((oc * 13 + trial * 5) % 97 - 48) * 0.011f;
}

int launch(void) {
  GuardedBuffer buffers[4] = {{0}};
  const size_t sizes[4] = {INPUT_COUNT, WEIGHT_COUNT, COUT, OUTPUT_COUNT};
  float *storage[4] = {x_storage, weight_storage, bias_storage, out_storage};
  for (int i = 0; i < 4; ++i) {
    if (buffer_init(&buffers[i], sizes[i], storage[i])) {
      for (int j = 0; j < i; ++j) buffer_free(&buffers[j]);
      return report_check("pwconv_cin144_cout576_h1_w1", 1, 0);
    }
  }
  float *x = buffers[0].data, *weight = buffers[1].data;
  float *bias = buffers[2].data, *out = buffers[3].data;
  unsigned errors = 0;
  double maximum = 0, maximum_ratio = 0, maximum_bound = 0;
  const double ku = (CIN + 2) * 0x1p-24;
  const double gamma = ku / (1.0 - ku);
  for (int trial = 0; trial < TRIALS; ++trial) {
    for (int ic = 0; ic < CIN; ++ic)
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w) x[(ic * H + h) * W + w] = x_value(ic, h, w, trial);
    for (int oc = 0; oc < COUT; ++oc) {
      bias[oc] = bias_value(oc, trial);
      for (int ic = 0; ic < CIN; ++ic) weight[oc * CIN + ic] = weight_value(oc, ic, trial);
    }
    for (int i = 0; i < OUTPUT_COUNT; ++i) out[i] = -9999.0f;
    run_pointwise_conv2d(x, weight, bias, out);
    /* Independent Conv2D oc/h/w/ic loops. Neither input nor output is
     * reinterpreted as [H*W,C]. No matrix library, im2col or Triton reference. */
    for (int oc = 0; oc < COUT; ++oc)
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w) {
          double sum = 0, magnitude = 0;
          for (int ic = 0; ic < CIN; ++ic) {
            double product = (double)x[(ic * H + h) * W + w] * (double)weight[oc * CIN + ic];
            sum += product;
            magnitude += product < 0 ? -product : product;
          }
          sum += (double)bias[oc];
          magnitude += bias[oc] < 0 ? -(double)bias[oc] : (double)bias[oc];
          double bound = gamma * magnitude + (CIN + 2) * 0x1p-149;
          if (bound > maximum_bound) maximum_bound = bound;
          float actual = out[(oc * H + h) * W + w];
          if (!__builtin_isfinite(actual)) {
            ++errors; maximum = __builtin_inf(); maximum_ratio = __builtin_inf();
          } else {
            double difference = (double)actual - sum;
            if (difference < 0) difference = -difference;
            errors += difference > bound;
            if (difference > maximum) maximum = difference;
            double ratio = difference / bound;
            if (ratio > maximum_ratio) maximum_ratio = ratio;
          }
        }
    for (int ic = 0; ic < CIN; ++ic)
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w)
          errors += float_bits(x[(ic * H + h) * W + w]) != float_bits(x_value(ic, h, w, trial));
    for (int oc = 0; oc < COUT; ++oc) {
      errors += float_bits(bias[oc]) != float_bits(bias_value(oc, trial));
      for (int ic = 0; ic < CIN; ++ic)
        errors += float_bits(weight[oc * CIN + ic]) != float_bits(weight_value(oc, ic, trial));
    }
    for (int i = 0; i < 4; ++i) errors += buffer_check(&buffers[i]);
  }
  for (int i = 0; i < 4; ++i) buffer_free(&buffers[i]);
#ifdef HOST_TEST
  printf("pointwise_conv2d metrics max_abs_error=%.17g max_error_over_bound=%.17g max_bound=%.17g\n",
         maximum, maximum_ratio, maximum_bound);
#endif
  return report_check("pwconv_cin144_cout576_h1_w1", errors, (float)maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
