#!/bin/bash
BUDDY_FRONTEND_GEN := ../../build/bin/buddy-frontendgen

opDefine:
	@${BUDDY_FRONTEND_GEN} -f ./opDefine.fegen

typeDefine:
	@${BUDDY_FRONTEND_GEN} -f ./typeDefine.fegen

rule:
	@${BUDDY_FRONTEND_GEN} -f ./rule.fegen

