//===- DequantMatMulVectorizationDecode.cpp
//--------------------------------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Fused dequantization + matmul vectorization for decode workloads (m==1).
//
// Matches the pattern generated by w8a32 quantization:
//   1. linalg.generic (arith.sitofp i8->f32) writes to cast_buf
//   2. linalg.generic (arith.mulf cast_buf, scale) writes to dequant_buf
//   3. linalg.matmul(A_f32, dequant_buf) -> C_f32
//
// Replaces the matmul with a fused vectorized kernel that:
//   - Reads int8 weights directly (4x less memory bandwidth)
//   - Casts to f32 and performs FMA in a single loop
//   - Applies per-channel scale after the reduction (factored out of k-loop)
//   - Eliminates the intermediate f32 dequantized weight buffer
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

using namespace mlir;

namespace {

struct DequantChain {
  Value i8Weight;   // Original i8 weight memref
  Value scale;      // Scale memref (f32)
  Value dequantBuf; // Intermediate dequantized buffer (to be eliminated)
  Value castBuf;    // Intermediate cast buffer (to be eliminated)
  linalg::GenericOp castOp;
  linalg::GenericOp mulOp;
  int scaleAxis; // Which axis the scale broadcasts over (non-1 dim)
};

static bool isSingleSitofpGeneric(linalg::GenericOp op) {
  if (op.getNumDpsInputs() != 1 || op.getNumDpsInits() != 1)
    return false;
  auto &body = op.getRegion().front();
  if (body.getNumArguments() != 2)
    return false;
  auto sitofpOp = dyn_cast<arith::SIToFPOp>(
      body.getTerminator()->getOperand(0).getDefiningOp());
  if (!sitofpOp)
    return false;
  if (sitofpOp.getOperand() != body.getArgument(0))
    return false;
  auto inType = dyn_cast<MemRefType>(op.getInputs()[0].getType());
  if (!inType)
    return false;
  return inType.getElementType().isInteger(8);
}

static bool isSingleMulfGeneric(linalg::GenericOp op) {
  if (op.getNumDpsInputs() != 2 || op.getNumDpsInits() != 1)
    return false;
  auto &body = op.getRegion().front();
  if (body.getNumArguments() != 3)
    return false;
  auto mulfOp = dyn_cast<arith::MulFOp>(
      body.getTerminator()->getOperand(0).getDefiningOp());
  if (!mulfOp)
    return false;
  auto lhs = mulfOp.getLhs();
  auto rhs = mulfOp.getRhs();
  return (lhs == body.getArgument(0) && rhs == body.getArgument(1)) ||
         (lhs == body.getArgument(1) && rhs == body.getArgument(0));
}

static std::optional<DequantChain> findDequantChain(Value matmulB) {
  // matmulB is the B operand of linalg.matmul (a memref)
  // We need to find linalg.generic ops that write into this memref.
  // Pattern: alloc -> cast_generic(i8_weight) -> mul_generic(cast_result,
  // scale)
  //          -> matmul uses mul_generic's output

  linalg::GenericOp mulGeneric = nullptr;
  for (auto *user : matmulB.getUsers()) {
    auto genOp = dyn_cast<linalg::GenericOp>(user);
    if (!genOp)
      continue;
    // Check if matmulB is one of the outputs of this generic
    for (auto output : genOp.getDpsInits()) {
      if (output == matmulB && isSingleMulfGeneric(genOp)) {
        mulGeneric = genOp;
        break;
      }
    }
    if (mulGeneric)
      break;
  }
  if (!mulGeneric)
    return std::nullopt;

  // Identify which input is the cast result and which is the scale
  Value castResult = mulGeneric.getInputs()[0];
  Value scaleInput = mulGeneric.getInputs()[1];

  // Find the cast generic that writes to castResult
  linalg::GenericOp castGeneric = nullptr;
  for (auto *user : castResult.getUsers()) {
    auto genOp = dyn_cast<linalg::GenericOp>(user);
    if (!genOp)
      continue;
    for (auto output : genOp.getDpsInits()) {
      if (output == castResult && isSingleSitofpGeneric(genOp)) {
        castGeneric = genOp;
        break;
      }
    }
    if (castGeneric)
      break;
  }

  if (!castGeneric) {
    // Try swapping: maybe scale is input[0] and cast is input[1]
    std::swap(castResult, scaleInput);
    for (auto *user : castResult.getUsers()) {
      auto genOp = dyn_cast<linalg::GenericOp>(user);
      if (!genOp)
        continue;
      for (auto output : genOp.getDpsInits()) {
        if (output == castResult && isSingleSitofpGeneric(genOp)) {
          castGeneric = genOp;
          break;
        }
      }
      if (castGeneric)
        break;
    }
    if (!castGeneric)
      return std::nullopt;
  }

  Value i8Weight = castGeneric.getInputs()[0];

  // Determine scale axis by looking at the mul generic's indexing maps
  auto indexingMaps = mulGeneric.getIndexingMapsArray();
  // indexingMaps[0] -> first input (cast result or scale)
  // indexingMaps[1] -> second input
  // indexingMaps[2] -> output
  // Find which input corresponds to the scale
  (void)indexingMaps; // Used for future extension

  // Find the scale axis (the non-broadcasted dimension)
  auto scaleType = dyn_cast<MemRefType>(scaleInput.getType());
  int scaleAxis = -1;
  if (scaleType) {
    for (int i = 0; i < (int)scaleType.getRank(); i++) {
      if (scaleType.getDimSize(i) != 1) {
        scaleAxis = i;
        break;
      }
    }
  }

  DequantChain chain;
  chain.i8Weight = i8Weight;
  chain.scale = scaleInput;
  chain.dequantBuf = matmulB;
  chain.castBuf = castResult;
  chain.castOp = castGeneric;
  chain.mulOp = mulGeneric;
  chain.scaleAxis = scaleAxis;
  return chain;
}

class DequantMatMulVectorizationDecodePattern : public ConversionPattern {
public:
  DequantMatMulVectorizationDecodePattern(MLIRContext *ctx, int64_t vecSize)
      : ConversionPattern(linalg::MatmulOp::getOperationName(), 2, ctx),
        vecSize(vecSize) {}

  LogicalResult
  matchAndRewrite(Operation *op, ArrayRef<Value> /*operands*/,
                  ConversionPatternRewriter &rewriter) const override {
    auto matmulOp = cast<linalg::MatmulOp>(op);
    auto loc = matmulOp.getLoc();

    Value A = matmulOp.getInputs()[0];
    Value B = matmulOp.getInputs()[1];
    Value C = matmulOp.getOutputs()[0];

    auto aType = dyn_cast<MemRefType>(A.getType());
    auto bType = dyn_cast<MemRefType>(B.getType());
    auto cType = dyn_cast<MemRefType>(C.getType());
    if (!aType || !bType || !cType)
      return failure();
    if (!aType.hasStaticShape() || aType.getRank() != 2)
      return failure();
    if (aType.getDimSize(0) != 1)
      return failure();
    if (cType.getRank() != 2 || cType.getDimSize(0) != 1)
      return failure();

    auto chain = findDequantChain(B);
    if (!chain)
      return failure();

    auto i8Type = dyn_cast<MemRefType>(chain->i8Weight.getType());
    auto scaleType = dyn_cast<MemRefType>(chain->scale.getType());
    if (!i8Type || !scaleType)
      return failure();

    Type f32Type = cType.getElementType();
    auto f32VecType = VectorType::get({vecSize}, f32Type);
    auto i8VecType = VectorType::get({vecSize}, rewriter.getI8Type());

    Value c0 = rewriter.create<arith::ConstantIndexOp>(loc, 0);
    Value c1 = rewriter.create<arith::ConstantIndexOp>(loc, 1);
    Value step = rewriter.create<arith::ConstantIndexOp>(loc, vecSize);

    Value n = rewriter.create<memref::DimOp>(loc, C, c1);
    Value k = rewriter.create<memref::DimOp>(loc, A, c1);

    Value zeroF32 = rewriter.create<arith::ConstantOp>(
        loc, f32Type, rewriter.getFloatAttr(f32Type, 0.0));
    Value zeroVec =
        rewriter.create<vector::BroadcastOp>(loc, f32VecType, zeroF32);

    // Determine scale load indices. For scale shape [1, N], the non-1 dim
    // is at axis 1, so we load scale[0, j].
    // For scale shape [K, 1], axis 0 is non-1, we load scale[k, 0].
    // For w8a32 matmul, scale should be along the N axis (last dim of weight).
    bool scaleAlongN = (chain->scaleAxis == (int)scaleType.getRank() - 1);

    rewriter.create<scf::ParallelOp>(
        loc,
        /*lowerBounds=*/ValueRange{c0},
        /*upperBounds=*/ValueRange{n},
        /*steps=*/ValueRange{step},
        [&](OpBuilder &builder, Location loc, ValueRange ivs) {
          Value nIdx = ivs.front();

          // Inner reduction loop over k, accumulating i8-cast-to-f32 * A
          auto sumIter = builder.create<scf::ForOp>(
              loc, c0, k, c1, ValueRange{zeroVec},
              [&](OpBuilder &builder, Location loc, Value kIdx,
                  ValueRange iterArgs) {
                // Load activation element A[0, k]
                Value aElem = builder.create<memref::LoadOp>(
                    loc, A, ValueRange{c0, kIdx});
                Value aVec =
                    builder.create<vector::BroadcastOp>(loc, f32VecType, aElem);

                // Load i8 weight vector B_i8[k, j:j+vecSize]
                Value bI8Vec = builder.create<vector::LoadOp>(
                    loc, i8VecType, chain->i8Weight, ValueRange{kIdx, nIdx});

                // Cast i8 -> f32
                Value bF32Vec =
                    builder.create<arith::SIToFPOp>(loc, f32VecType, bI8Vec);

                // FMA: acc += A[0,k] * (float)B_i8[k,j]
                Value res = builder.create<vector::FMAOp>(loc, aVec, bF32Vec,
                                                          iterArgs.front());

                builder.create<scf::YieldOp>(loc, res);
              });

          Value accVec = sumIter.getResult(0);

          // Apply per-channel scale: acc * scale[j]
          // Load scale vector (handling the broadcasting dimension)
          Value scaleVec;
          if (scaleAlongN) {
            // scale shape [1, N] or similar - load along N axis
            SmallVector<Value> scaleIndices;
            for (int i = 0; i < (int)scaleType.getRank(); i++) {
              if (i == chain->scaleAxis)
                scaleIndices.push_back(nIdx);
              else
                scaleIndices.push_back(c0);
            }
            scaleVec = builder.create<vector::LoadOp>(
                loc, f32VecType, chain->scale, scaleIndices);
          } else {
            // Fallback: load scale as scalar and broadcast
            SmallVector<Value> scaleIndices(scaleType.getRank(), c0);
            Value scaleScalar =
                builder.create<memref::LoadOp>(loc, chain->scale, scaleIndices);
            scaleVec = builder.create<vector::BroadcastOp>(loc, f32VecType,
                                                           scaleScalar);
          }

          Value scaledVec =
              builder.create<arith::MulFOp>(loc, accVec, scaleVec);

          // Add to existing C value (for correctness if C is pre-initialized)
          Value cVec = builder.create<vector::LoadOp>(loc, f32VecType, C,
                                                      ValueRange{c0, nIdx});
          Value resultVec = builder.create<arith::AddFOp>(loc, cVec, scaledVec);

          builder.create<vector::StoreOp>(loc, resultVec, C,
                                          ValueRange{c0, nIdx});
        });

    rewriter.eraseOp(op);

    // Clean up the dead dequant chain. ConversionPatternRewriter defers
    // erasures, so we track all erased ops to exclude from use-checks.
    SmallPtrSet<Operation *, 4> erasedOps;
    erasedOps.insert(op); // the just-erased matmul

    auto canErase = [&](Value buf, Operation *producer) -> bool {
      for (auto *user : buf.getUsers()) {
        if (user == producer || erasedOps.contains(user))
          continue;
        if (isa<memref::DeallocOp>(user))
          continue;
        return false;
      }
      return true;
    };

    auto eraseBufferChain = [&](Value buf, Operation *producer) {
      SmallVector<Operation *> toErase;
      for (auto *user : buf.getUsers()) {
        if (isa<memref::DeallocOp>(user))
          toErase.push_back(user);
      }
      for (auto *deadOp : toErase) {
        rewriter.eraseOp(deadOp);
        erasedOps.insert(deadOp);
      }
      rewriter.eraseOp(producer);
      erasedOps.insert(producer);
      if (auto allocOp = buf.getDefiningOp()) {
        rewriter.eraseOp(allocOp);
        erasedOps.insert(allocOp);
      }
    };

    if (canErase(chain->dequantBuf, chain->mulOp))
      eraseBufferChain(chain->dequantBuf, chain->mulOp);

    if (canErase(chain->castBuf, chain->castOp))
      eraseBufferChain(chain->castBuf, chain->castOp);

    return success();
  }

private:
  int64_t vecSize;
};

class DequantMatMulVectorizationDecodePass
    : public PassWrapper<DequantMatMulVectorizationDecodePass,
                         OperationPass<ModuleOp>> {
public:
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(
      DequantMatMulVectorizationDecodePass)

  StringRef getArgument() const final {
    return "dequant-matmul-vectorization-decode";
  }
  StringRef getDescription() const final {
    return "Fused dequant+matmul vectorization for w8a32 decode (m==1). "
           "Reads i8 weights directly and applies scale after reduction.";
  }

  DequantMatMulVectorizationDecodePass() = default;
  DequantMatMulVectorizationDecodePass(
      const DequantMatMulVectorizationDecodePass &) {}

  void getDependentDialects(DialectRegistry &registry) const override {
    registry.insert<linalg::LinalgDialect, scf::SCFDialect,
                    vector::VectorDialect, arith::ArithDialect>();
  }

  void runOnOperation() override {
    MLIRContext *context = &getContext();
    ModuleOp module = getOperation();

    ConversionTarget target(*context);
    target.addLegalDialect<arith::ArithDialect, memref::MemRefDialect,
                           scf::SCFDialect, vector::VectorDialect,
                           func::FuncDialect, linalg::LinalgDialect>();
    target.addLegalOp<ModuleOp, func::FuncOp, func::ReturnOp>();
    target.addDynamicallyLegalOp<linalg::MatmulOp>(
        [&](linalg::MatmulOp op) -> bool {
          auto aType = dyn_cast<MemRefType>(op.getInputs()[0].getType());
          auto cType = dyn_cast<MemRefType>(op.getOutputs()[0].getType());
          if (!aType || !cType)
            return true;
          if (!aType.hasStaticShape() || aType.getRank() != 2)
            return true;
          if (aType.getDimSize(0) != 1)
            return true;
          if (cType.getRank() != 2 || cType.getDimSize(0) != 1)
            return true;
          Value B = op.getInputs()[1];
          auto chain = findDequantChain(B);
          if (!chain)
            return true; // No dequant chain, legal (leave for normal pass)
          return false;  // Has dequant chain, illegal (needs rewriting)
        });

    RewritePatternSet patterns(context);
    patterns.add<DequantMatMulVectorizationDecodePattern>(context, vectorSize);

    if (failed(applyPartialConversion(module, target, std::move(patterns))))
      signalPassFailure();
  }

  Option<int64_t> vectorSize{
      *this, "vector-size",
      llvm::cl::desc("Vector width for n-dimension iteration."),
      llvm::cl::init(32)};
};

} // namespace

namespace mlir {
namespace buddy {
void registerDequantMatMulVectorizationDecodePass() {
  PassRegistration<DequantMatMulVectorizationDecodePass>();
}
} // namespace buddy
} // namespace mlir
