//===- Int4DequantMatMulVectorizationDecode.cpp
//----------------------------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Fused int4-unpack + dequantization + matmul vectorization for W4A16 decode.
//
// Matches the pattern generated by w4a16 quantization after bufferization:
//   1. Int4 unpack chain:
//      andi(packed, 0x0F) -> shli(_, 4) -> shrsi(_, 4) [low nibbles]
//      shrsi(packed, 4)                                 [high nibbles]
//      reshape+concat -> [K, N] unpacked i8 buffer
//   2. linalg.generic (arith.sitofp i8->f16) -> cast_buf
//   3. linalg.generic (arith.mulf cast_buf, scale) -> dequant_buf
//   4. linalg.matmul(A_f16, dequant_buf) -> C_f16
//
// Replaces everything with a fused vectorized kernel that:
//   - Reads packed int4 weights directly (8x less bandwidth vs f16)
//   - Performs in-register unpacking via bitwise ops + vector.interleave
//   - Casts to f16 and performs FMA in a single loop
//   - Applies per-channel scale after the reduction
//   - Eliminates all intermediate buffers
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

using namespace mlir;

namespace {

// --- Dequant chain (reused logic from DequantMatMulVectorizationDecode) ------

struct DequantChain {
  Value i8Weight;
  Value scale;
  Value dequantBuf;
  Value castBuf;
  linalg::GenericOp castOp;
  linalg::GenericOp mulOp;
  int scaleAxis;
};

static bool isSingleSitofpGeneric(linalg::GenericOp op) {
  if (op.getNumDpsInputs() != 1 || op.getNumDpsInits() != 1)
    return false;
  auto &body = op.getRegion().front();
  if (body.getNumArguments() != 2)
    return false;
  auto sitofpOp = dyn_cast<arith::SIToFPOp>(
      body.getTerminator()->getOperand(0).getDefiningOp());
  if (!sitofpOp || sitofpOp.getOperand() != body.getArgument(0))
    return false;
  auto inType = dyn_cast<MemRefType>(op.getInputs()[0].getType());
  return inType && inType.getElementType().isInteger(8);
}

static bool isSingleMulfGeneric(linalg::GenericOp op) {
  if (op.getNumDpsInputs() != 2 || op.getNumDpsInits() != 1)
    return false;
  auto &body = op.getRegion().front();
  if (body.getNumArguments() != 3)
    return false;
  auto mulfOp = dyn_cast<arith::MulFOp>(
      body.getTerminator()->getOperand(0).getDefiningOp());
  if (!mulfOp)
    return false;
  auto lhs = mulfOp.getLhs();
  auto rhs = mulfOp.getRhs();
  return (lhs == body.getArgument(0) && rhs == body.getArgument(1)) ||
         (lhs == body.getArgument(1) && rhs == body.getArgument(0));
}

static std::optional<DequantChain> findDequantChain(Value matmulB) {
  linalg::GenericOp mulGeneric = nullptr;
  for (auto *user : matmulB.getUsers()) {
    auto genOp = dyn_cast<linalg::GenericOp>(user);
    if (!genOp)
      continue;
    for (auto output : genOp.getDpsInits()) {
      if (output == matmulB && isSingleMulfGeneric(genOp)) {
        mulGeneric = genOp;
        break;
      }
    }
    if (mulGeneric)
      break;
  }
  if (!mulGeneric)
    return std::nullopt;

  Value castResult = mulGeneric.getInputs()[0];
  Value scaleInput = mulGeneric.getInputs()[1];

  linalg::GenericOp castGeneric = nullptr;
  for (auto *user : castResult.getUsers()) {
    auto genOp = dyn_cast<linalg::GenericOp>(user);
    if (!genOp)
      continue;
    for (auto output : genOp.getDpsInits()) {
      if (output == castResult && isSingleSitofpGeneric(genOp)) {
        castGeneric = genOp;
        break;
      }
    }
    if (castGeneric)
      break;
  }

  if (!castGeneric) {
    std::swap(castResult, scaleInput);
    for (auto *user : castResult.getUsers()) {
      auto genOp = dyn_cast<linalg::GenericOp>(user);
      if (!genOp)
        continue;
      for (auto output : genOp.getDpsInits()) {
        if (output == castResult && isSingleSitofpGeneric(genOp)) {
          castGeneric = genOp;
          break;
        }
      }
      if (castGeneric)
        break;
    }
    if (!castGeneric)
      return std::nullopt;
  }

  Value i8Weight = castGeneric.getInputs()[0];

  auto scaleType = dyn_cast<MemRefType>(scaleInput.getType());
  int scaleAxis = -1;
  if (scaleType) {
    for (int i = 0; i < (int)scaleType.getRank(); i++) {
      if (scaleType.getDimSize(i) != 1) {
        scaleAxis = i;
        break;
      }
    }
  }

  DequantChain chain;
  chain.i8Weight = i8Weight;
  chain.scale = scaleInput;
  chain.dequantBuf = matmulB;
  chain.castBuf = castResult;
  chain.castOp = castGeneric;
  chain.mulOp = mulGeneric;
  chain.scaleAxis = scaleAxis;
  return chain;
}

// --- Int4 unpack chain tracing ---

struct Int4UnpackInfo {
  Value packedWeight; // Original packed i8 buffer [K, N/2]
  Value concatBuf;    // The [K, N/2, 2] concat buffer
  SmallVector<Operation *> allOps;
  SmallVector<Value> allBuffers;
};

static linalg::GenericOp findProducerGeneric(Value buf) {
  for (auto *user : buf.getUsers()) {
    auto gen = dyn_cast<linalg::GenericOp>(user);
    if (!gen)
      continue;
    for (auto out : gen.getDpsInits()) {
      if (out == buf)
        return gen;
    }
  }
  return nullptr;
}

static bool bodyHasOnlyOp(linalg::GenericOp gen,
                          llvm::function_ref<bool(Operation *)> pred) {
  auto &body = gen.getRegion().front();
  auto yieldOp = cast<linalg::YieldOp>(body.getTerminator());
  auto *defOp = yieldOp.getOperand(0).getDefiningOp();
  return defOp && pred(defOp);
}

static std::optional<Int4UnpackInfo> findInt4UnpackChain(Value i8Weight) {
  // i8Weight should be reinterpret_cast from [K, N/2, 2] to [K, N]
  auto rcOp = i8Weight.getDefiningOp<memref::ReinterpretCastOp>();
  if (!rcOp)
    return std::nullopt;

  Value concatBuf = rcOp.getSource();
  auto concatType = dyn_cast<MemRefType>(concatBuf.getType());
  if (!concatType || concatType.getRank() != 3 || concatType.getDimSize(2) != 2)
    return std::nullopt;

  if (!concatBuf.getDefiningOp<memref::AllocOp>())
    return std::nullopt;

  Int4UnpackInfo info;
  info.concatBuf = concatBuf;
  info.allBuffers.push_back(concatBuf);

  // Find two memref.copy ops that write into slices of concatBuf.
  // Each target is a ReinterpretCastOp of concatBuf with stride-2 layout.
  SmallVector<memref::CopyOp> copies;
  for (auto *user : concatBuf.getUsers()) {
    auto sliceRC = dyn_cast<memref::ReinterpretCastOp>(user);
    if (!sliceRC || sliceRC == rcOp)
      continue;
    info.allOps.push_back(sliceRC);
    for (auto *sliceUser : sliceRC.getResult().getUsers()) {
      auto cp = dyn_cast<memref::CopyOp>(sliceUser);
      if (cp && cp.getTarget() == sliceRC.getResult()) {
        copies.push_back(cp);
        info.allOps.push_back(cp);
      }
    }
  }
  if (copies.size() != 2)
    return std::nullopt;

  Value packedBuf = nullptr;

  for (auto cp : copies) {
    Value src = cp.getSource();
    // src is reinterpret_cast of nibble buf [K, N/2] to [K, N/2, 1]
    auto srcRC = src.getDefiningOp<memref::ReinterpretCastOp>();
    if (!srcRC)
      return std::nullopt;
    info.allOps.push_back(srcRC);

    Value nibbleBuf = srcRC.getSource();
    info.allBuffers.push_back(nibbleBuf);

    auto producer = findProducerGeneric(nibbleBuf);
    if (!producer)
      return std::nullopt;

    // Producer should be a shrsi generic
    if (!bodyHasOnlyOp(producer,
                       [](Operation *op) { return isa<arith::ShRSIOp>(op); }))
      return std::nullopt;
    info.allOps.push_back(producer);

    Value firstInput = producer.getInputs()[0];

    // Check if firstInput is produced by a shli generic (low path)
    auto shliProducer = findProducerGeneric(firstInput);
    if (shliProducer && bodyHasOnlyOp(shliProducer, [](Operation *op) {
          return isa<arith::ShLIOp>(op);
        })) {
      // Low path: shrsi <- shli <- andi <- packed
      info.allOps.push_back(shliProducer);
      info.allBuffers.push_back(firstInput);

      Value andiInput = shliProducer.getInputs()[0];
      auto andiProducer = findProducerGeneric(andiInput);
      if (!andiProducer || !bodyHasOnlyOp(andiProducer, [](Operation *op) {
            return isa<arith::AndIOp>(op);
          }))
        return std::nullopt;
      info.allOps.push_back(andiProducer);
      info.allBuffers.push_back(andiInput);

      Value candidate = andiProducer.getInputs()[0];
      if (packedBuf && packedBuf != candidate)
        return std::nullopt;
      packedBuf = candidate;
    } else {
      // High path: shrsi(packed, shift)
      if (packedBuf && packedBuf != firstInput)
        return std::nullopt;
      packedBuf = firstInput;
    }
  }

  if (!packedBuf)
    return std::nullopt;

  auto packedType = dyn_cast<MemRefType>(packedBuf.getType());
  if (!packedType || packedType.getRank() != 2 ||
      !packedType.getElementType().isInteger(8))
    return std::nullopt;

  info.packedWeight = packedBuf;
  return info;
}

// --- Combined chain check ---

static bool hasInt4DequantChain(Value matmulB) {
  auto dchain = findDequantChain(matmulB);
  if (!dchain)
    return false;
  return findInt4UnpackChain(dchain->i8Weight).has_value();
}

// --- Rewrite pattern ---

class Int4DequantMatMulPattern : public ConversionPattern {
public:
  Int4DequantMatMulPattern(MLIRContext *ctx, int64_t vecSize)
      : ConversionPattern(linalg::MatmulOp::getOperationName(), 3, ctx),
        vecSize(vecSize) {}

  LogicalResult
  matchAndRewrite(Operation *op, ArrayRef<Value> /*operands*/,
                  ConversionPatternRewriter &rewriter) const override {
    auto matmulOp = cast<linalg::MatmulOp>(op);
    auto loc = matmulOp.getLoc();

    Value A = matmulOp.getInputs()[0];
    Value B = matmulOp.getInputs()[1];
    Value C = matmulOp.getOutputs()[0];

    auto aType = dyn_cast<MemRefType>(A.getType());
    auto cType = dyn_cast<MemRefType>(C.getType());
    if (!aType || !cType)
      return failure();
    if (!aType.hasStaticShape() || aType.getRank() != 2)
      return failure();
    if (aType.getDimSize(0) != 1)
      return failure();
    if (cType.getRank() != 2 || cType.getDimSize(0) != 1)
      return failure();

    auto dchain = findDequantChain(B);
    if (!dchain)
      return failure();

    auto unpackInfo = findInt4UnpackChain(dchain->i8Weight);
    if (!unpackInfo)
      return failure();

    auto scaleType = dyn_cast<MemRefType>(dchain->scale.getType());
    if (!scaleType)
      return failure();

    Type elemType = cType.getElementType();
    auto floatVecType = VectorType::get({vecSize}, elemType);
    auto halfI8VecType = VectorType::get({vecSize / 2}, rewriter.getI8Type());
    Value c0 = rewriter.create<arith::ConstantIndexOp>(loc, 0);
    Value c1 = rewriter.create<arith::ConstantIndexOp>(loc, 1);
    Value c2 = rewriter.create<arith::ConstantIndexOp>(loc, 2);
    Value step = rewriter.create<arith::ConstantIndexOp>(loc, vecSize);

    Value N = rewriter.create<memref::DimOp>(loc, C, c1);
    Value K = rewriter.create<memref::DimOp>(loc, A, c1);

    Value zeroFloat = rewriter.create<arith::ConstantOp>(
        loc, elemType, rewriter.getFloatAttr(elemType, 0.0));
    Value zeroVec =
        rewriter.create<vector::BroadcastOp>(loc, floatVecType, zeroFloat);
    Value mask15 = rewriter.create<arith::ConstantOp>(
        loc,
        DenseElementsAttr::get(halfI8VecType, rewriter.getI8IntegerAttr(15)));
    Value shift4 = rewriter.create<arith::ConstantOp>(
        loc,
        DenseElementsAttr::get(halfI8VecType, rewriter.getI8IntegerAttr(4)));

    bool scaleAlongN = (dchain->scaleAxis == (int)scaleType.getRank() - 1);

    Value packedWeight = unpackInfo->packedWeight;

    rewriter.create<scf::ParallelOp>(
        loc, ValueRange{c0}, ValueRange{N}, ValueRange{step},
        [&](OpBuilder &builder, Location loc, ValueRange ivs) {
          Value nIdx = ivs.front();

          // Packed index = nIdx / 2
          Value packedIdx = builder.create<arith::DivUIOp>(loc, nIdx, c2);

          auto forOp = builder.create<scf::ForOp>(
              loc, c0, K, c1, ValueRange{zeroVec},
              [&](OpBuilder &builder, Location loc, Value kIdx,
                  ValueRange iterArgs) {
                // Load activation A[0, k]
                Value aElem = builder.create<memref::LoadOp>(
                    loc, A, ValueRange{c0, kIdx});
                Value aVec = builder.create<vector::BroadcastOp>(
                    loc, floatVecType, aElem);

                // Load vecSize/2 packed bytes
                Value packedVec = builder.create<vector::LoadOp>(
                    loc, halfI8VecType, packedWeight,
                    ValueRange{kIdx, packedIdx});

                // Unpack low nibbles: (byte & 0x0F) << 4 >> 4
                Value lowMasked =
                    builder.create<arith::AndIOp>(loc, packedVec, mask15);
                Value lowShifted =
                    builder.create<arith::ShLIOp>(loc, lowMasked, shift4);
                Value low =
                    builder.create<arith::ShRSIOp>(loc, lowShifted, shift4);

                // Unpack high nibbles: byte >> 4
                Value high =
                    builder.create<arith::ShRSIOp>(loc, packedVec, shift4);

                // Interleave: [low0, high0, low1, high1, ...]
                Value unpacked =
                    builder.create<vector::InterleaveOp>(loc, low, high);

                // Cast i8 -> float
                Value floatVec = builder.create<arith::SIToFPOp>(
                    loc, floatVecType, unpacked);

                // FMA: acc += a * float_weight
                Value res = builder.create<vector::FMAOp>(loc, aVec, floatVec,
                                                          iterArgs.front());

                builder.create<scf::YieldOp>(loc, res);
              });

          Value accVec = forOp.getResult(0);

          // Apply per-channel scale
          Value scaleVec;
          if (scaleAlongN) {
            SmallVector<Value> scaleIndices;
            for (int i = 0; i < (int)scaleType.getRank(); i++) {
              if (i == dchain->scaleAxis)
                scaleIndices.push_back(nIdx);
              else
                scaleIndices.push_back(c0);
            }
            scaleVec = builder.create<vector::LoadOp>(
                loc, floatVecType, dchain->scale, scaleIndices);
          } else {
            SmallVector<Value> scaleIndices(scaleType.getRank(), c0);
            Value scaleScalar = builder.create<memref::LoadOp>(
                loc, dchain->scale, scaleIndices);
            scaleVec = builder.create<vector::BroadcastOp>(loc, floatVecType,
                                                           scaleScalar);
          }

          Value scaledVec =
              builder.create<arith::MulFOp>(loc, accVec, scaleVec);

          // Add to existing C
          Value cVec = builder.create<vector::LoadOp>(loc, floatVecType, C,
                                                      ValueRange{c0, nIdx});
          Value resultVec = builder.create<arith::AddFOp>(loc, cVec, scaledVec);

          builder.create<vector::StoreOp>(loc, resultVec, C,
                                          ValueRange{c0, nIdx});
        });

    rewriter.eraseOp(op);

    // --- Cleanup: remove dead dequant + unpack chains ---
    SmallPtrSet<Operation *, 16> erasedOps;
    erasedOps.insert(op);

    auto canErase = [&](Value buf, Operation *producer) -> bool {
      for (auto *user : buf.getUsers()) {
        if (user == producer || erasedOps.contains(user))
          continue;
        if (isa<memref::DeallocOp>(user))
          continue;
        return false;
      }
      return true;
    };

    auto eraseBufferChain = [&](Value buf, Operation *producer) {
      SmallVector<Operation *> toErase;
      for (auto *user : buf.getUsers()) {
        if (isa<memref::DeallocOp>(user))
          toErase.push_back(user);
      }
      for (auto *deadOp : toErase) {
        rewriter.eraseOp(deadOp);
        erasedOps.insert(deadOp);
      }
      rewriter.eraseOp(producer);
      erasedOps.insert(producer);
      if (auto allocOp = buf.getDefiningOp()) {
        rewriter.eraseOp(allocOp);
        erasedOps.insert(allocOp);
      }
    };

    // Clean dequant chain (mulf output, sitofp output)
    if (canErase(dchain->dequantBuf, dchain->mulOp))
      eraseBufferChain(dchain->dequantBuf, dchain->mulOp);

    if (canErase(dchain->castBuf, dchain->castOp))
      eraseBufferChain(dchain->castBuf, dchain->castOp);

    // Erase the reinterpret_cast [K,N] that defined i8Weight
    if (auto *rcDef = dchain->i8Weight.getDefiningOp()) {
      if (!erasedOps.contains(rcDef)) {
        bool noLiveUsers = true;
        for (auto *user : dchain->i8Weight.getUsers()) {
          if (!erasedOps.contains(user)) {
            noLiveUsers = false;
            break;
          }
        }
        if (noLiveUsers) {
          rewriter.eraseOp(rcDef);
          erasedOps.insert(rcDef);
        }
      }
    }

    // Clean int4 unpack chain: ops first, then buffers.
    for (auto *unpackOp : llvm::reverse(unpackInfo->allOps)) {
      if (!erasedOps.contains(unpackOp)) {
        rewriter.eraseOp(unpackOp);
        erasedOps.insert(unpackOp);
      }
    }

    for (auto buf : llvm::reverse(unpackInfo->allBuffers)) {
      for (auto *user : buf.getUsers()) {
        if (isa<memref::DeallocOp>(user) && !erasedOps.contains(user)) {
          rewriter.eraseOp(user);
          erasedOps.insert(user);
        }
      }
      if (auto *defOp = buf.getDefiningOp()) {
        if (!erasedOps.contains(defOp)) {
          bool allUsersDead = true;
          for (auto *user : buf.getUsers()) {
            if (!erasedOps.contains(user)) {
              allUsersDead = false;
              break;
            }
          }
          if (allUsersDead) {
            rewriter.eraseOp(defOp);
            erasedOps.insert(defOp);
          }
        }
      }
    }

    return success();
  }

private:
  int64_t vecSize;
};

// --- Pass definition ---

class Int4DequantMatMulVectorizationDecodePass
    : public PassWrapper<Int4DequantMatMulVectorizationDecodePass,
                         OperationPass<ModuleOp>> {
public:
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(
      Int4DequantMatMulVectorizationDecodePass)

  StringRef getArgument() const final {
    return "int4-dequant-matmul-vectorization-decode";
  }
  StringRef getDescription() const final {
    return "Fused int4-unpack+dequant+matmul vectorization for W4A16 decode "
           "(m==1). Reads packed i4 weights directly and unpacks in-register.";
  }

  Int4DequantMatMulVectorizationDecodePass() = default;
  Int4DequantMatMulVectorizationDecodePass(
      const Int4DequantMatMulVectorizationDecodePass &) {}

  void getDependentDialects(DialectRegistry &registry) const override {
    registry.insert<linalg::LinalgDialect, scf::SCFDialect,
                    vector::VectorDialect, arith::ArithDialect>();
  }

  void runOnOperation() override {
    MLIRContext *context = &getContext();
    ModuleOp module = getOperation();

    ConversionTarget target(*context);
    target.addLegalDialect<arith::ArithDialect, memref::MemRefDialect,
                           scf::SCFDialect, vector::VectorDialect,
                           func::FuncDialect, linalg::LinalgDialect>();
    target.addLegalOp<ModuleOp, func::FuncOp, func::ReturnOp>();
    target.addDynamicallyLegalOp<linalg::MatmulOp>(
        [](linalg::MatmulOp op) -> bool {
          auto aType = dyn_cast<MemRefType>(op.getInputs()[0].getType());
          auto cType = dyn_cast<MemRefType>(op.getOutputs()[0].getType());
          if (!aType || !cType)
            return true;
          if (!aType.hasStaticShape() || aType.getRank() != 2)
            return true;
          if (aType.getDimSize(0) != 1)
            return true;
          if (cType.getRank() != 2 || cType.getDimSize(0) != 1)
            return true;
          return !hasInt4DequantChain(op.getInputs()[1]);
        });

    RewritePatternSet patterns(context);
    patterns.add<Int4DequantMatMulPattern>(context, vectorSize);

    if (failed(applyPartialConversion(module, target, std::move(patterns))))
      signalPassFailure();
  }

  Option<int64_t> vectorSize{
      *this, "vector-size",
      llvm::cl::desc("Vector width for n-dimension iteration."),
      llvm::cl::init(32)};
};

} // namespace

namespace mlir {
namespace buddy {
void registerInt4DequantMatMulVectorizationDecodePass() {
  PassRegistration<Int4DequantMatMulVectorizationDecodePass>();
}
} // namespace buddy
} // namespace mlir
