/* Generated by triton/cases.py; independent C ReLU oracle. */
#include "support.h"
#define COUNT 68992
#define BLOCK 128
#ifndef HOST_TEST
static float x_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define out_storage NULL
#endif
static float reference[COUNT] WORKSPACE;
extern void run_relu(float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int i, int trial) {
  /* Every case, including COUNT=8, contains negatives, both signed zeros,
   * positives and the largest finite FP32 magnitudes. Repeat at the tail. */
  static const uint32_t edges[8] = {
    0xc1000000u, 0x80000000u, 0x00000000u, 0x40600000u,
    0xbe800000u, 0x3e800000u, 0xff7fffffu, 0x7f7fffffu
  };
  if (i < 8 || i >= COUNT - 8) {
    union { uint32_t u; float f; } bits = {edges[(i + trial * 3) % 8]};
    return bits.f;
  }
  return (float)((i * 17 + trial * 13) % 257 - 128) * 0.125f;
}

int launch(void) {
  GuardedBuffer x = {0}, out = {0};
  if (buffer_init(&x, COUNT, x_storage)) return report_check("relu_count68992", 1, 0);
  if (buffer_init(&out, COUNT, out_storage)) {
    buffer_free(&x); return report_check("relu_count68992", 1, 0);
  }
  unsigned errors = 0;
  float maximum = 0;
  for (int trial = 0; trial < 2; ++trial) {
    unsigned negatives = 0, positives = 0, plus_zero = 0, minus_zero = 0;
    for (int i = 0; i < COUNT; ++i) {
      x.data[i] = x_value(i, trial);
      out.data[i] = -9999.0f;
      negatives += x.data[i] < 0.0f;
      positives += x.data[i] > 0.0f;
      plus_zero += float_bits(x.data[i]) == 0x00000000u;
      minus_zero += float_bits(x.data[i]) == 0x80000000u;
    }
    errors += !negatives || !positives || !plus_zero || !minus_zero;
    /* Reference computed independently before calling the compiled kernel. */
    for (int i = 0; i < COUNT; ++i)
      reference[i] = x.data[i] > 0.0f ? x.data[i] : 0.0f;
    run_relu(x.data, out.data);
    for (int i = 0; i < COUNT; ++i) {
      if (!__builtin_isfinite(out.data[i])) {
        ++errors; maximum = __builtin_inff();
      } else {
        /* Numeric equality intentionally accepts either zero sign. */
        errors += out.data[i] != reference[i];
        float difference = out.data[i] - reference[i];
        if (difference < 0) difference = -difference;
        if (difference > maximum) maximum = difference;
      }
      /* Input immutability is checked bitwise, including the sign of zero. */
      errors += float_bits(x.data[i]) != float_bits(x_value(i, trial));
    }
    errors += buffer_check(&x) + buffer_check(&out);
  }
  buffer_free(&x); buffer_free(&out);
  return report_check("relu_count68992", errors, maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
