#!/usr/bin/env python3
# ruff: noqa: E501
# ===- gen_session.py - Generate C++ ModelSession from config --------------===//
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ===----------------------------------------------------------------------===//
#
# Generates ModelSession.h and ModelSession.cpp from a full model config.
# The generated code handles:
#   - KVCacheABI struct (N KV MemRefs + logits MemRef)
#   - PrefillFn / DecodeFn function pointer types
#   - dlopen/dlsym, placement-new KV cache, decode call expansion
#
# Usage:
#   python gen_session.py --config deepseek_r1_f32.json --output-dir build/generated/
#   # emits build/generated/buddy/runtime/models/ModelSession.h and
#   #       build/generated/ModelSession.cpp
#
# ===----------------------------------------------------------------------===//

import argparse
import json
import os
import sys
from io import StringIO

# Prologues for generated C++ (LLVM-style file banner + Apache + scope notes).
_H_FILE_PROLOGUE = """\
//===- ModelSession.h - Runtime session for DeepSeek R1 (generated) ----------===//
//
// Auto-generated by tools/buddy-codegen/gen_session.py — DO NOT EDIT.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// ModelSession owns all persistent state for one inference session:
//   - KV cache buffers (one MemRef per layer), managed via BufferPool
//   - Logits output buffer
//   - Decode position counter
//   - Loaded model .so handle (dlopen/dlclose lifecycle)
//   - Weight tensors (loaded via loadWeights() from paths in the manifest or CLI)
//
// Host code calls loadWeights(), then prefill() / decode().
//
//===----------------------------------------------------------------------===//
"""

_CPP_FILE_PROLOGUE = """\
//===- ModelSession.cpp - ModelSession implementation (generated) ------------===//
//
// Auto-generated by tools/buddy-codegen/gen_session.py — DO NOT EDIT.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Dynamic-loading version: dlopen/dlsym, no static model symbols.
//
// Notes on MemRef default constructor:
//   Container.h declares MemRef(){} as *protected*, so we cannot
//   default-construct array members. We work around this by storing the
//   KV MemRef objects in raw char storage (KVCacheABI below) and
//   initialising them via placement new in allocateKVCache().
//
//===----------------------------------------------------------------------===//
"""


def _macro_prefix(config: dict) -> str:
    """Return the C macro prefix, e.g. BUDDY_DSR1."""
    family = config["model_family"].upper()
    short = {"DEEPSEEK_R1": "DSR1"}.get(family, family)
    return f"BUDDY_{short}"


# ──────────────────────────────────────────────────────────────────────────────
# Header generation
# ──────────────────────────────────────────────────────────────────────────────


def gen_header(config: dict) -> str:
    out = StringIO()

    def _p(*a, **kw):
        print(*a, file=out, **kw)

    p = _p

    mp = _macro_prefix(config)
    shape = config["shape"]
    weights = config["weights"]
    logits_cpp = config["cpp_types"]["logits"]
    kv_layers = shape["kv_layers"]
    need_logits_conv = logits_cpp != "float"
    guard = "BUDDY_RUNTIME_MODELS_MODELSESSION_H"

    p(_H_FILE_PROLOGUE)
    p(f"#ifndef {guard}")
    p(f"#define {guard}")
    p()
    p('#include "buddy/runtime/core/BufferPool.h"')
    p('#include "buddy/runtime/core/ModelManifest.h"')
    p('#include "buddy/runtime/llm/LLMSession.h"')
    p()
    p('#include "buddy/Core/Container.h"')
    p('#include "buddy/LLM/TextContainer.h"')
    p()
    p("#include <cstdint>")
    p("#include <memory>")
    p("#include <string>")
    p("#include <vector>")
    p()

    # Shape constant macros with #ifndef guards
    defaults = {
        "HEAD_NUM": shape["head_num"],
        "MAX_TOKEN_LEN": shape["max_token_len"],
        "HIDDEN_SIZE": shape["hidden_size"],
        "VOCAB_SIZE": shape["vocab_size"],
        "KV_LAYERS": kv_layers,
    }
    for w in weights:
        tag_upper = w["tag"].upper()
        val = w["num_elements"]
        suffix = "LL" if val > 1_000_000_000 else ""
        defaults[f"PARAMS_SIZE_{tag_upper}"] = f"{val}{suffix}"

    if len(weights) == 1:
        w0 = weights[0]
        val = w0["num_elements"]
        suffix = "LL" if val > 1_000_000_000 else ""
        defaults["PARAMS_SIZE"] = f"{val}{suffix}"

    for name, val in defaults.items():
        macro = f"{mp}_{name}"
        p(f"#ifndef {macro}")
        p(f"#define {macro} {val}")
        p("#endif")

    p()
    p("namespace buddy {")
    p("namespace runtime {")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// ModelSession")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()
    p(
        "/// Encapsulates one inference session for this model variant (shapes and"
    )
    p("/// weight layout come from the generated macros above).")
    p("///")
    p("/// Typical workflow: loadWeights() → prefill() → decode() in a loop.")
    p()
    p("class ModelSession : public LLMSession {")
    p("public:")
    p("  struct Config {")
    p("    /// Path to the runtime-loadable model shared library (dlopen).")
    p("    std::string modelSoPath;")
    p(
        "    /// Optional dependent shared libraries to preload before modelSoPath."
    )
    p("    std::vector<std::string> dependentSoPaths;")
    p(f"    int headNum = {mp}_HEAD_NUM;")
    p(f"    int maxTokenLen = {mp}_MAX_TOKEN_LEN;")
    p(f"    int hiddenSize = {mp}_HIDDEN_SIZE;")
    p(f"    int vocabSize = {mp}_VOCAB_SIZE;")
    p(f"    int kvLayers = {mp}_KV_LAYERS;")
    p("  };")
    p()
    p("  /// Allocates KV cache, then dlopen + dlsym. Throws on failure.")
    p("  static std::unique_ptr<ModelSession> create(const Config &cfg);")
    p(
        "  /// Build from a packed .rax manifest (fills resolvedManifest with paths)."
    )
    p("  static std::unique_ptr<ModelSession>")
    p(
        "  createFromRax(const std::string &raxPath, ModelManifest &resolvedManifest);"
    )
    p()
    p("  ~ModelSession() override;")
    p("  // Non-copyable")
    p("  ModelSession(const ModelSession &) = delete;")
    p("  ModelSession &operator=(const ModelSession &) = delete;")
    p()
    p(
        "  /// Load all weight blobs from disk (order matches the compiled manifest)."
    )
    p(
        "  void loadWeights(const std::vector<std::string> &weightPaths) override;"
    )
    p(
        "  /// Run prefill over the prompt tokens (weights must be loaded first)."
    )
    p("  void prefill(Text<size_t, 2> &tokens) override;")
    p("  /// One decode step for a single token id.")
    p("  void decode(int tokenId) override;")
    p()
    p("  void resetPosition() override;")
    p("  /// KV overflow: discard tokens and fix RoPE on surviving keys.")
    p("  bool handleKVCacheOverflow(int keepTokenNum,")
    p("                             float ropeTheta = 10000.0f) override;")
    p("  int position() const override { return position_; }")
    p(
        "  /// Logits for one position; non-f32 logits may be converted to float."
    )
    p("  const float *logitsData(int tokenOffset = 0) const override;")
    p("  int vocabSize() const override { return cfg_.vocabSize; }")
    p("  std::string loadedSoPath() const;")
    p("  const BufferPool &bufferPool() const { return pool_; }")
    p()
    p("private:")
    p("  explicit ModelSession(const Config &cfg);")
    p("  void allocateKVCache();")
    p()
    p("  Config cfg_;")
    p("  BufferPool pool_;")
    p("  int position_ = 0;")
    p()
    p("  // Pimpl: KVCacheABI, dlopen handle, and function pointers.")
    p("  struct Impl;")
    p("  std::unique_ptr<Impl> impl_;")
    p()
    p("  // Decode step inputs (reused every call).")
    p("  std::unique_ptr<MemRef<long long, 2>> decodeTokenInput_;")
    p("  std::unique_ptr<MemRef<long long, 1>> cachePosition_;")
    p()

    # Weight storage members (one MemRef per external constant in the manifest).
    for w in weights:
        memref_t = f"MemRef<{w['cpp_type']}, 1>"
        p(f"  std::unique_ptr<{memref_t}> {w['tag']}_;")

    if need_logits_conv:
        p("  // Scratch buffer when logits are not stored as float (e.g. f16).")
        p("  mutable std::vector<float> logitsFloat_;")

    p("};")
    p()
    p("} // namespace runtime")
    p("} // namespace buddy")
    p()
    p(f"#endif // {guard}")
    p()

    return out.getvalue()


# ──────────────────────────────────────────────────────────────────────────────
# Implementation generation
# ──────────────────────────────────────────────────────────────────────────────


def gen_impl(config: dict) -> str:
    out = StringIO()

    def _p(*a, **kw):
        print(*a, file=out, **kw)

    p = _p

    mp = _macro_prefix(config)
    shape = config["shape"]
    weights = config["weights"]
    variant = config["variant"]
    kv_cpp = config["cpp_types"]["kv"]
    logits_cpp = config["cpp_types"]["logits"]
    kv_layers = shape["kv_layers"]
    kv_memref = config["cpp_types"]["kv_memref"]
    logits_memref = config["cpp_types"]["logits_memref"]
    need_logits_conv = logits_cpp != "float"
    is_quantized = variant.startswith("w")

    p(_CPP_FILE_PROLOGUE)
    p('#include "buddy/runtime/models/ModelSession.h"')
    p('#include "buddy/runtime/llm/KVCacheManager.h"')
    p()
    p("#include <cstring>")
    p("#include <dlfcn.h>")
    p("#include <fstream>")
    p("#include <stdexcept>")
    p("#include <string>")
    p()
    p(
        "// std::launder is in <new> (C++17). Use it when accessing a MemRef object"
    )
    p("// through a char* pointer obtained by reinterpret_cast.")
    p("#include <new> // for std::launder, placement new")
    p()
    p("namespace buddy {")
    p("namespace runtime {")
    p()

    # ── Half-to-float helper (emitted only when needed) ──────────────────────
    if need_logits_conv:
        p("namespace {")
        p("inline float halfToFloat(uint16_t h) {")
        p("  uint32_t sign = (uint32_t)(h >> 15) << 31;")
        p("  uint32_t exp = (h >> 10) & 0x1f;")
        p("  uint32_t mant = h & 0x3ff;")
        p("  uint32_t f;")
        p("  if (exp == 0)")
        p(
            "    f = (mant == 0) ? sign : sign | ((127 - 14) << 23) | (mant << 13);"
        )
        p("  else if (exp == 31)")
        p("    f = sign | 0x7f800000u | (mant << 13);")
        p("  else")
        p("    f = sign | ((exp + 127 - 15) << 23) | (mant << 13);")
        p("  float result;")
        p("  std::memcpy(&result, &f, 4);")
        p("  return result;")
        p("}")
        p("} // namespace")
        p()

    # ── PrefillABI / DecodeABI ───────────────────────────────────────────────
    dummy_groups = kv_layers // 2 - 1
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p(
        "// PrefillABI / DecodeABI — contiguous memory blocks for the MLIR result"
    )
    p("// structs")
    p("//")
    p("// _mlir_ciface_forward_prefill writes:")
    p(
        f"//   [kv0..kv{kv_layers - 1} : {kv_memref} x {kv_layers}]"
        f"[logits : {logits_memref}]"
    )
    p("//")
    p("// _mlir_ciface_forward_decode writes:")
    p("//   [cache_position_out : MemRef<long long, 1>]")
    if is_quantized:
        p(
            f"//   [kv0][kv1][dummy0..dummy{dummy_groups - 1}]"
            f"[kv2..kv{kv_layers - 1}][logits]"
        )
    else:
        p(
            f"//   [kv0][kv1][dummy0][kv2][kv3][dummy1] ... "
            f"[kv{kv_layers - 2}][kv{kv_layers - 1}][logits]"
        )
    p("//")
    p(
        "// Because MemRef<T,N>() is protected, we store these objects in char arrays"
    )
    p("// and construct/destruct them explicitly via placement new.")
    p(
        "// The pointer arithmetic uses sizeof(MemRef<...>) for correct alignment (alignas)."
    )
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()
    p("using Dummy1Ref = MemRef<long long, 1>;")
    p(f"using KV4Ref = {kv_memref};")
    p(f"using Logits3Ref = {logits_memref};")
    p()
    if not is_quantized:
        p("struct DecodeKVGroup {")
        p("  alignas(Dummy1Ref) char dummy_[sizeof(Dummy1Ref)];")
        p("  alignas(KV4Ref) char kv0_[sizeof(KV4Ref)];")
        p("  alignas(KV4Ref) char kv1_[sizeof(KV4Ref)];")
        p()
        p("  Dummy1Ref &dummy() {")
        p("    return *std::launder(reinterpret_cast<Dummy1Ref *>(dummy_));")
        p("  }")
        p("  KV4Ref &kv0() {")
        p("    return *std::launder(reinterpret_cast<KV4Ref *>(kv0_));")
        p("  }")
        p("  KV4Ref &kv1() {")
        p("    return *std::launder(reinterpret_cast<KV4Ref *>(kv1_));")
        p("  }")
        p("};")
        p()
    p("struct PrefillABI {")
    p(f"  alignas({kv_memref}) char kv_[sizeof({kv_memref}) *")
    p(f"                                     {mp}_KV_LAYERS];")
    p(f"  alignas({logits_memref}) char logits_[sizeof({logits_memref})];")
    p()
    p(f"  {kv_memref} &kv(int i) {{")
    p(f"    return *std::launder(reinterpret_cast<{kv_memref} *>(")
    p(f"        kv_ + i * sizeof({kv_memref})));")
    p("  }")
    p(f"  {logits_memref} &logits() {{")
    p(
        f"    return *std::launder(reinterpret_cast<{logits_memref} *>(logits_));"
    )
    p("  }")
    p("};")
    p()
    p("struct DecodeABI {")
    p("  alignas(Dummy1Ref) char cache_position_out_[sizeof(Dummy1Ref)];")
    p("  alignas(KV4Ref) char kv0_[sizeof(KV4Ref)];")
    p("  alignas(KV4Ref) char kv1_[sizeof(KV4Ref)];")
    if is_quantized:
        p(
            f"  alignas(Dummy1Ref) char dummy_[sizeof(Dummy1Ref) * {dummy_groups}];"
        )
        p(
            f"  alignas(KV4Ref) char remaining_kv_[sizeof(KV4Ref) * ({mp}_KV_LAYERS - 2)];"
        )
    else:
        p(f"  DecodeKVGroup groups_[{dummy_groups}];")
    p("  alignas(Logits3Ref) char logits_[sizeof(Logits3Ref)];")
    p()
    p("  Dummy1Ref &cachePositionOut() {")
    p(
        "    return *std::launder("
        "reinterpret_cast<Dummy1Ref *>(cache_position_out_));"
    )
    p("  }")
    if is_quantized:
        p("  Dummy1Ref &dummy(int i) {")
        p("    return *std::launder(reinterpret_cast<Dummy1Ref *>(")
        p("        dummy_ + i * sizeof(Dummy1Ref)));")
        p("  }")
    else:
        p("  Dummy1Ref &dummy(int i) { return groups_[i].dummy(); }")
    p("  KV4Ref &kv(int i) {")
    p("    if (i == 0)")
    p("      return *std::launder(reinterpret_cast<KV4Ref *>(kv0_));")
    p("    if (i == 1)")
    p("      return *std::launder(reinterpret_cast<KV4Ref *>(kv1_));")
    if is_quantized:
        p("    return *std::launder(reinterpret_cast<KV4Ref *>(")
        p("        remaining_kv_ + (i - 2) * sizeof(KV4Ref)));")
    else:
        p("    int group = (i - 2) / 2;")
        p(
            "    return ((i - 2) % 2 == 0) ? groups_[group].kv0() : groups_[group].kv1();"
        )
    p("  }")
    p("  Logits3Ref &logits() {")
    p("    return *std::launder(reinterpret_cast<Logits3Ref *>(logits_));")
    p("  }")
    p("};")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// Function pointer types (private to this TU)")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── Function pointer types ───────────────────────────────────────────────
    weight_ptr_types = ", ".join(
        f"MemRef<{w['cpp_type']}, 1> *" for w in weights
    )

    p(
        f"using PrefillFn = void (*)(PrefillABI *, {weight_ptr_types}, Text<size_t, 2> *);"
    )
    p()

    kv4 = "KV4Ref *"
    dummy1 = "Dummy1Ref *"
    p(f"using KV4 = {kv4};")
    p(f"using Dummy1 = {dummy1};")
    p()
    decode_sig_parts = [
        "DecodeABI *",
        *[f"MemRef<{w['cpp_type']}, 1> *" for w in weights],
        "MemRef<long long, 2> *",
        "MemRef<long long, 1> *",
        "KV4",
        "KV4",
    ]
    for _i in range(dummy_groups):
        decode_sig_parts.extend(["Dummy1", "KV4", "KV4"])
    p("using DecodeFn = void (*)(")
    line = "    "
    for idx, part in enumerate(decode_sig_parts):
        sep = "," if idx < len(decode_sig_parts) - 1 else ");"
        candidate = line + part + sep + " "
        if len(candidate) > 78 and line.strip():
            p(line.rstrip())
            line = "    " + part + sep + " "
        else:
            line = candidate
    if line.strip():
        p(line.rstrip())
    p()

    # ── Impl struct ──────────────────────────────────────────────────────────
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// ModelSession::Impl")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()
    p("struct ModelSession::Impl {")
    p("  PrefillABI prefillAbi;")
    p("  DecodeABI decodeAbi;")
    p("  bool abiInitialized = false;  // placement-new has been called")
    p("  void *soHandle = nullptr;")
    p("  std::vector<void *> depSoHandles;")
    p("  PrefillFn prefillFn = nullptr;")
    p("  DecodeFn decodeFn = nullptr;")
    p("  bool lastLogitsAreDecode = false;")
    p()
    p("  ~Impl() {")
    p(
        "    // Explicitly destroy placement-new'd objects before releasing the .so."
    )
    p("    if (abiInitialized) {")
    p(f"      for (int i = 0; i < {mp}_KV_LAYERS; ++i)")
    p(f"        prefillAbi.kv(i).~{kv_memref}();")
    p(f"      prefillAbi.logits().~{logits_memref}();")
    p("      decodeAbi.cachePositionOut().~Dummy1Ref();")
    p(f"      for (int i = 0; i < {dummy_groups}; ++i)")
    p("        decodeAbi.dummy(i).~Dummy1Ref();")
    p(f"      for (int i = 0; i < {mp}_KV_LAYERS; ++i)")
    p(f"        decodeAbi.kv(i).~{kv_memref}();")
    p(f"      decodeAbi.logits().~{logits_memref}();")
    p("    }")
    p("    if (soHandle) {")
    p("      dlclose(soHandle);")
    p("      soHandle = nullptr;")
    p("    }")
    p(
        "    for (auto it = depSoHandles.rbegin(); it != depSoHandles.rend(); ++it) {"
    )
    p("      if (*it)")
    p("        dlclose(*it);")
    p("    }")
    p("    depSoHandles.clear();")
    p("  }")
    p()
    p(
        "  /// Preload dependent shared libs, then dlopen model and resolve symbols."
    )
    p("  void loadSo(const std::string &soPath,")
    p("              const std::vector<std::string> &dependentSoPaths) {")
    p("    for (const auto &depPath : dependentSoPaths) {")
    p(
        "      void *depHandle = dlopen(depPath.c_str(), RTLD_NOW | RTLD_GLOBAL);"
    )
    p("      if (!depHandle)")
    p(
        '        throw std::runtime_error("[BuddyRuntime] dependent dlopen failed: " + depPath +'
    )
    p('                                 "\\n  " + dlerror());')
    p("      depSoHandles.push_back(depHandle);")
    p("    }")
    p()
    p("    soHandle = dlopen(soPath.c_str(), RTLD_NOW | RTLD_LOCAL);")
    p("    if (!soHandle)")
    p(
        '      throw std::runtime_error("[BuddyRuntime] dlopen failed: " + soPath +'
    )
    p('                               "\\n  " + dlerror());')
    p()
    p("    prefillFn = reinterpret_cast<PrefillFn>(")
    p('        dlsym(soHandle, "_mlir_ciface_forward_prefill"));')
    p("    if (!prefillFn)")
    p("      throw std::runtime_error(")
    p(
        '          "[BuddyRuntime] symbol not found: _mlir_ciface_forward_prefill\\n  " +'
    )
    p("          std::string(dlerror()));")
    p()
    p("    decodeFn = reinterpret_cast<DecodeFn>(")
    p('        dlsym(soHandle, "_mlir_ciface_forward_decode"));')
    p("    if (!decodeFn)")
    p("      throw std::runtime_error(")
    p(
        '          "[BuddyRuntime] symbol not found: _mlir_ciface_forward_decode\\n  " +'
    )
    p("          std::string(dlerror()));")
    p("  }")
    p("};")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// ModelSession lifecycle")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── Lifecycle ────────────────────────────────────────────────────────────
    p("ModelSession::ModelSession(const Config &cfg) : cfg_(cfg) {")
    p("  if (cfg_.modelSoPath.empty())")
    p("    throw std::runtime_error(")
    p('        "[BuddyRuntime] Config.modelSoPath must not be empty.");')
    p("  allocateKVCache();")
    p("  impl_->loadSo(cfg_.modelSoPath, cfg_.dependentSoPaths);")
    p("}")
    p()
    p("ModelSession::~ModelSession() = default;")
    p()
    p("std::unique_ptr<ModelSession> ModelSession::create(const Config &cfg) {")
    p("  return std::unique_ptr<ModelSession>(new ModelSession(cfg));")
    p("}")
    p()

    # ── allocateKVCache ──────────────────────────────────────────────────────
    kv_sizeof = f"sizeof({kv_cpp})"

    p("void ModelSession::allocateKVCache() {")
    p("  impl_ = std::make_unique<Impl>();")
    p()
    p("  const uint64_t elemsPerLayer =")
    p("      (uint64_t)cfg_.headNum * cfg_.maxTokenLen * cfg_.hiddenSize;")
    p(f"  const uint64_t bytesPerLayer = elemsPerLayer * {kv_sizeof};")
    p()
    p("  // --- KV cache: one MemRef per layer, constructed in-place ---")
    p(
        "  intptr_t kvShape[4] = {1, cfg_.headNum, cfg_.maxTokenLen, cfg_.hiddenSize};"
    )
    p("  intptr_t pshape[1] = {1};")
    p()
    p("  {")
    p("    BufferDesc desc;")
    p('    desc.name = "cache_position_out";')
    p("    desc.role = BufferRole::Output;")
    p("    desc.lifetime = BufferLifetime::Session;")
    p("    desc.bytes = sizeof(long long);")
    p("    desc.id = 250;")
    p()
    p("    new (&impl_->decodeAbi.cachePositionOut()) Dummy1Ref(pshape, 0LL);")
    p("    impl_->decodeAbi.cachePositionOut().getData()[0] = 0LL;")
    p("  }")
    p()
    p("  for (int i = 0; i < cfg_.kvLayers; ++i) {")
    p("    BufferDesc desc;")
    p('    desc.name = "kv" + std::to_string(i);')
    p("    desc.role = BufferRole::State;")
    p("    desc.lifetime = BufferLifetime::Session;")
    p("    desc.bytes = bytesPerLayer;")
    p("    desc.id = (uint32_t)(100 + i);")
    p()
    p("    auto &bv = pool_.allocate(desc);")
    p(
        "    // Placement-new: construct a MemRef view into the BufferPool buffer."
    )
    p("    new (&impl_->prefillAbi.kv(i))")
    p(f"        {kv_memref}(reinterpret_cast<{kv_cpp} *>(bv.data), kvShape);")
    p("    new (&impl_->decodeAbi.kv(i))")
    p(f"        {kv_memref}(reinterpret_cast<{kv_cpp} *>(bv.data), kvShape);")
    p("  }")
    p()
    p(f"  for (int i = 0; i < {dummy_groups}; ++i) {{")
    p("    new (&impl_->decodeAbi.dummy(i)) Dummy1Ref(pshape, 0LL);")
    p("    impl_->decodeAbi.dummy(i).getData()[0] = 0LL;")
    p("  }")
    p()
    p("  // --- Logits: prefill shape {1, maxTokenLen, vocabSize} ---")
    p("  const uint64_t prefillLogitsBytes =")
    p(f"      (uint64_t)cfg_.maxTokenLen * cfg_.vocabSize * {kv_sizeof};")
    p("  {")
    p("    BufferDesc desc;")
    p('    desc.name = "prefill_logits";')
    p("    desc.role = BufferRole::Output;")
    p("    desc.lifetime = BufferLifetime::Session;")
    p("    desc.bytes = prefillLogitsBytes;")
    p("    desc.id = 200;")
    p()
    p("    auto &bv = pool_.allocate(desc);")
    p("    intptr_t lshape[3] = {1, cfg_.maxTokenLen, cfg_.vocabSize};")
    p("    new (&impl_->prefillAbi.logits())")
    p(
        f"        {logits_memref}(reinterpret_cast<{logits_cpp} *>(bv.data), lshape);"
    )
    p("  }")
    p()
    p("  {")
    p("    BufferDesc desc;")
    p('    desc.name = "decode_logits";')
    p("    desc.role = BufferRole::Output;")
    p("    desc.lifetime = BufferLifetime::Session;")
    p(f"    desc.bytes = (uint64_t)cfg_.vocabSize * {kv_sizeof};")
    p("    desc.id = 201;")
    p()
    p("    auto &bv = pool_.allocate(desc);")
    p("    intptr_t lshape[3] = {1, 1, cfg_.vocabSize};")
    p("    new (&impl_->decodeAbi.logits())")
    p(
        f"        {logits_memref}(reinterpret_cast<{logits_cpp} *>(bv.data), lshape);"
    )
    p("  }")
    p()
    p("  impl_->abiInitialized = true;")
    p()
    p("  // --- Decode step inputs (small, reused every call) ---")
    p("  {")
    p("    intptr_t tshape[2] = {1, 1};")
    p("    decodeTokenInput_ = std::make_unique<MemRef<long long, 2>>(tshape);")
    p("    cachePosition_ = std::make_unique<MemRef<long long, 1>>(pshape);")
    p("  }")
    p("}")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// loadWeights")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── loadWeights ──────────────────────────────────────────────────────────
    p("void ModelSession::loadWeights(const std::vector<std::string> &paths) {")
    p(f"  if (paths.size() < {len(weights)}u)")
    p(
        f'    throw std::runtime_error("[BuddyRuntime] Expected {len(weights)} weight '
        f'file(s), got " + std::to_string(paths.size()));'
    )
    p()
    for idx, w in enumerate(weights):
        tag = w["tag"]
        cpp_type = w["cpp_type"]
        macro_suffix = (
            "PARAMS_SIZE" if len(weights) == 1 else f"PARAMS_SIZE_{tag.upper()}"
        )
        p("  {")
        p(f"    intptr_t shape[1] = {{{mp}_{macro_suffix}}};")
        p(f"    {tag}_ = std::make_unique<MemRef<{cpp_type}, 1>>(shape);")
        p(f"    std::ifstream f(paths[{idx}], std::ios::binary);")
        p("    if (!f)")
        p(
            f'      throw std::runtime_error("[BuddyRuntime] Cannot open weights: " + '
            f"paths[{idx}]);"
        )
        p(f"    f.read(reinterpret_cast<char *>({tag}_->getData()),")
        p(f"           sizeof({cpp_type}) * {tag}_->getSize());")
        p("    if (f.fail())")
        p(
            f'      throw std::runtime_error("[BuddyRuntime] Read failed: " + '
            f"paths[{idx}]);"
        )
        p("  }")
    p("}")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// Prefill")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── prefill ──────────────────────────────────────────────────────────────
    weight_addrs_internal = ", ".join(f"{w['tag']}_.get()" for w in weights)

    p("void ModelSession::prefill(Text<size_t, 2> &tokens) {")
    p(
        f"  impl_->prefillFn(&impl_->prefillAbi, {weight_addrs_internal}, &tokens);"
    )
    p("  const uint64_t elemsPerLayer =")
    p("      (uint64_t)cfg_.headNum * cfg_.maxTokenLen * cfg_.hiddenSize;")
    p("  for (int i = 0; i < cfg_.kvLayers; ++i) {")
    p("    std::memcpy(impl_->decodeAbi.kv(i).getData(),")
    p("                impl_->prefillAbi.kv(i).getData(),")
    p(f"                elemsPerLayer * {kv_sizeof});")
    p("  }")
    p("  impl_->lastLogitsAreDecode = false;")
    p("  int tokenCount = (int)tokens.getTokenCnt();")
    p("  position_ = tokenCount;")
    p("}")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// Decode")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── decode ───────────────────────────────────────────────────────────────
    p("void ModelSession::decode(int tokenId) {")
    p("  decodeTokenInput_->getData()[0] = (long long)tokenId;")
    p("  cachePosition_->getData()[0] = (long long)position_;")
    p()
    p("  auto &a = impl_->decodeAbi;")
    p(f"  for (int i = 0; i < {dummy_groups}; ++i)")
    p("    a.dummy(i).getData()[0] = (long long)position_;")

    call_parts = ["&a"]
    for w in weights:
        call_parts.append(f"{w['tag']}_.get()")
    call_parts.append("decodeTokenInput_.get()")
    call_parts.append("cachePosition_.get()")
    call_parts.extend(["&a.kv(0)", "&a.kv(1)"])
    for i in range(dummy_groups):
        call_parts.extend(
            [f"&a.dummy({i})", f"&a.kv({2 + i * 2})", f"&a.kv({3 + i * 2})"]
        )

    p("  impl_->decodeFn(")
    line = "      "
    for idx, part in enumerate(call_parts):
        sep = ", " if idx < len(call_parts) - 1 else ");"
        candidate = line + part + sep
        if len(candidate) > 80 and line.strip():
            p(line.rstrip(", ") + ",")
            line = "      " + part + sep
        else:
            line = candidate
    if line.strip():
        p(line)

    p()
    p("  impl_->lastLogitsAreDecode = true;")
    p("  position_ += 1;")
    p("}")
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// Misc")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p()

    # ── Misc methods ─────────────────────────────────────────────────────────
    p("void ModelSession::resetPosition() {")
    p("  position_ = 0;")
    p("  impl_->lastLogitsAreDecode = false;")
    p("}")
    p()

    p(
        "bool ModelSession::handleKVCacheOverflow(int keepTokenNum, float ropeTheta) {"
    )
    p("  if (position_ < cfg_.maxTokenLen)")
    p("    return false;")
    p()
    p("  const int currentTokens = std::min(position_, cfg_.maxTokenLen);")
    p("  keepTokenNum = std::clamp(keepTokenNum, 0, currentTokens - 1);")
    p(
        "  const int discardLen = std::max(1, (currentTokens - keepTokenNum) / 2);"
    )
    p()
    p("  // Extract raw pointers from KV cache MemRefs for kvcache helpers.")
    p(f"  {kv_cpp} *rawPtrs[{mp}_KV_LAYERS];")
    p("  for (int i = 0; i < cfg_.kvLayers; ++i)")
    p("    rawPtrs[i] = impl_->decodeAbi.kv(i).getData();")
    p()
    p("  // Step 1: Discard tokens (memmove + memset).")
    p("  buddy::kvcache::discardKVCache(rawPtrs, cfg_.kvLayers, cfg_.headNum,")
    p("                                 cfg_.maxTokenLen, cfg_.hiddenSize,")
    p(
        "                                 keepTokenNum, discardLen, currentTokens);"
    )
    p()
    p(
        "  // Step 2: Adjust RoPE on surviving tail (now relocated to keepTokenNum)."
    )
    p("  auto inverseFreqs =")
    p(
        "      buddy::kvcache::buildInverseRopeFreqs(ropeTheta, cfg_.hiddenSize);"
    )
    p("  buddy::kvcache::adjustKeyCacheRope(")
    p(
        "      rawPtrs, cfg_.kvLayers, cfg_.headNum, cfg_.maxTokenLen, cfg_.hiddenSize,"
    )
    p("      keepTokenNum, discardLen, currentTokens, inverseFreqs);")
    p()
    p("  // Step 3: Update position.")
    p(
        "  position_ = std::clamp(currentTokens - discardLen, 0, cfg_.maxTokenLen);"
    )
    p("  return true;")

    p("}")
    p()

    # ── logitsData ───────────────────────────────────────────────────────────
    if need_logits_conv:
        p("const float *ModelSession::logitsData(int tokenOffset) const {")
        p("  const int n = cfg_.vocabSize;")
        p("  if ((int)logitsFloat_.size() != n)")
        p("    logitsFloat_.resize(n);")
        p(f"  const {logits_cpp} *raw = nullptr;")
        p("  if (impl_->lastLogitsAreDecode) {")
        p("    raw = impl_->decodeAbi.logits().getData();")
        p("  } else {")
        p(
            "    raw = impl_->prefillAbi.logits().getData() + (size_t)tokenOffset * n;"
        )
        p("  }")
        p("  for (int i = 0; i < n; ++i)")
        p("    logitsFloat_[i] = halfToFloat(raw[i]);")
        p("  return logitsFloat_.data();")
        p("}")
    else:
        p("const float *ModelSession::logitsData(int tokenOffset) const {")
        p("  if (impl_->lastLogitsAreDecode)")
        p("    return impl_->decodeAbi.logits().getData();")
        p(
            "  return impl_->prefillAbi.logits().getData() + "
            "(size_t)tokenOffset * cfg_.vocabSize;"
        )
        p("}")
    p()
    p(
        "std::string ModelSession::loadedSoPath() const { return cfg_.modelSoPath; }"
    )
    p()
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// createFromRax: load config from a packed .rax manifest")
    p(
        "//===----------------------------------------------------------------------===//"
    )
    p("// Shape constants remain at compile-time defaults from macros;")
    p(
        "// createFromRax() sets cfg.modelSoPath and cfg.dependentSoPaths from manifest."
    )
    p()

    # ── createFromRax ────────────────────────────────────────────────────────
    p("std::unique_ptr<ModelSession>")
    p("ModelSession::createFromRax(const std::string &raxPath,")
    p("                            ModelManifest &resolvedManifest) {")
    p("  resolvedManifest = ModelManifest::loadFromRax(raxPath);")
    p("  Config cfg;")
    p("  cfg.modelSoPath = resolvedManifest.soPath;")
    p("  cfg.dependentSoPaths = resolvedManifest.dependentSoPaths;")
    p("  return create(cfg);")
    p("}")
    p()
    p("} // namespace runtime")
    p("} // namespace buddy")
    p()

    return out.getvalue()


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ ModelSession .h/.cpp from a full model config."
    )
    parser.add_argument(
        "--config", required=True, help="Path to full config JSON"
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help=(
            "Output root: writes buddy/runtime/models/ModelSession.h and "
            "ModelSession.cpp (no other copies; CMake uses build dir only)."
        ),
    )
    args = parser.parse_args()

    with open(args.config) as f:
        config = json.load(f)

    os.makedirs(args.output_dir, exist_ok=True)
    h_dir = os.path.join(args.output_dir, "buddy", "runtime", "models")
    os.makedirs(h_dir, exist_ok=True)

    h_path = os.path.join(h_dir, "ModelSession.h")
    cpp_path = os.path.join(args.output_dir, "ModelSession.cpp")

    with open(h_path, "w") as f:
        f.write(gen_header(config))
    print(f"[gen_session] Written: {h_path}", file=sys.stderr)

    with open(cpp_path, "w") as f:
        f.write(gen_impl(config))
    print(f"[gen_session] Written: {cpp_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
