// Auto-generated by tools/buddy-codegen/gen_session.py — DO NOT EDIT.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "buddy/runtime/models/ModelSession.h"
#include "buddy/runtime/llm/KVCacheManager.h"

#include <cstring>
#include <dlfcn.h>
#include <fstream>
#include <new>
#include <stdexcept>
#include <string>

namespace buddy {
namespace runtime {

namespace {
inline float halfToFloat(uint16_t h) {
  uint32_t sign = (uint32_t)(h >> 15) << 31;
  uint32_t exp = (h >> 10) & 0x1f;
  uint32_t mant = h & 0x3ff;
  uint32_t f;
  if (exp == 0)
    f = (mant == 0) ? sign : sign | ((127 - 14) << 23) | (mant << 13);
  else if (exp == 31)
    f = sign | 0x7f800000u | (mant << 13);
  else
    f = sign | ((exp + 127 - 15) << 23) | (mant << 13);
  float result;
  std::memcpy(&result, &f, 4);
  return result;
}
} // namespace

struct KVCacheABI {
  alignas(MemRef<uint16_t, 4>) char kv_[sizeof(MemRef<uint16_t, 4>) *
                                        BUDDY_DSR1_KV_LAYERS];
  alignas(MemRef<uint16_t, 3>) char logits_[sizeof(MemRef<uint16_t, 3>)];

  MemRef<uint16_t, 4> &kv(int i) {
    return *std::launder(reinterpret_cast<MemRef<uint16_t, 4> *>(
        kv_ + i * sizeof(MemRef<uint16_t, 4>)));
  }
  MemRef<uint16_t, 3> &logits() {
    return *std::launder(reinterpret_cast<MemRef<uint16_t, 3> *>(logits_));
  }
};

using PrefillFn = void (*)(KVCacheABI *, MemRef<uint16_t, 1> *,
                           MemRef<int8_t, 1> *, Text<size_t, 2> *);

using KV4 = MemRef<uint16_t, 4> *;
using DecodeFn = void (*)(KVCacheABI *, MemRef<uint16_t, 1> *,
                          MemRef<int8_t, 1> *, MemRef<long long, 2> *,
                          MemRef<long long, 1> *, KV4, KV4, KV4, KV4, KV4, KV4,
                          KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4,
                          KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4,
                          KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4,
                          KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4, KV4,
                          KV4, KV4, KV4, KV4, KV4, KV4);

struct ModelSession::Impl {
  KVCacheABI abi;
  MemRef<uint16_t, 4> *kvPtrs[BUDDY_DSR1_KV_LAYERS];
  bool abiInitialized = false;
  void *soHandle = nullptr;
  PrefillFn prefillFn = nullptr;
  DecodeFn decodeFn = nullptr;

  ~Impl() {
    if (abiInitialized) {
      for (int i = 0; i < BUDDY_DSR1_KV_LAYERS; ++i)
        abi.kv(i).~MemRef<uint16_t, 4>();
      abi.logits().~MemRef<uint16_t, 3>();
    }
    if (soHandle) {
      dlclose(soHandle);
      soHandle = nullptr;
    }
  }

  void loadSo(const std::string &soPath) {
    soHandle = dlopen(soPath.c_str(), RTLD_NOW | RTLD_LOCAL);
    if (!soHandle)
      throw std::runtime_error("[BuddyRuntime] dlopen failed: " + soPath +
                               "\n  " + dlerror());

    prefillFn = reinterpret_cast<PrefillFn>(
        dlsym(soHandle, "_mlir_ciface_forward_prefill"));
    if (!prefillFn)
      throw std::runtime_error(
          "[BuddyRuntime] symbol not found: _mlir_ciface_forward_prefill\n  " +
          std::string(dlerror()));

    decodeFn = reinterpret_cast<DecodeFn>(
        dlsym(soHandle, "_mlir_ciface_forward_decode"));
    if (!decodeFn)
      throw std::runtime_error(
          "[BuddyRuntime] symbol not found: _mlir_ciface_forward_decode\n  " +
          std::string(dlerror()));
  }
};

ModelSession::ModelSession(const Config &cfg) : cfg_(cfg) {
  if (cfg_.modelSoPath.empty())
    throw std::runtime_error(
        "[BuddyRuntime] Config.modelSoPath must not be empty.");
  allocateKVCache();
  impl_->loadSo(cfg_.modelSoPath);
}

ModelSession::~ModelSession() = default;

std::unique_ptr<ModelSession> ModelSession::create(const Config &cfg) {
  return std::unique_ptr<ModelSession>(new ModelSession(cfg));
}

void ModelSession::allocateKVCache() {
  impl_ = std::make_unique<Impl>();

  const uint64_t elemsPerLayer =
      (uint64_t)cfg_.headNum * cfg_.maxTokenLen * cfg_.hiddenSize;
  const uint64_t bytesPerLayer = elemsPerLayer * sizeof(uint16_t);

  intptr_t kvShape[4] = {1, cfg_.headNum, cfg_.maxTokenLen, cfg_.hiddenSize};

  for (int i = 0; i < cfg_.kvLayers; ++i) {
    BufferDesc desc;
    desc.name = "kv" + std::to_string(i);
    desc.role = BufferRole::State;
    desc.lifetime = BufferLifetime::Session;
    desc.bytes = bytesPerLayer;
    desc.id = (uint32_t)(100 + i);

    auto &bv = pool_.allocate(desc);
    new (&impl_->abi.kv(i))
        MemRef<uint16_t, 4>(reinterpret_cast<uint16_t *>(bv.data), kvShape);
    impl_->kvPtrs[i] = &impl_->abi.kv(i);
  }

  const uint64_t logitsBytes =
      (uint64_t)cfg_.maxTokenLen * cfg_.vocabSize * sizeof(uint16_t);
  {
    BufferDesc desc;
    desc.name = "logits";
    desc.role = BufferRole::Output;
    desc.lifetime = BufferLifetime::Session;
    desc.bytes = logitsBytes;
    desc.id = 200;

    auto &bv = pool_.allocate(desc);
    intptr_t lshape[3] = {1, cfg_.maxTokenLen, cfg_.vocabSize};
    new (&impl_->abi.logits())
        MemRef<uint16_t, 3>(reinterpret_cast<uint16_t *>(bv.data), lshape);
  }

  impl_->abiInitialized = true;

  {
    intptr_t tshape[2] = {1, 1};
    decodeTokenInput_ = std::make_unique<MemRef<long long, 2>>(tshape);
    intptr_t pshape[1] = {1};
    cachePosition_ = std::make_unique<MemRef<long long, 1>>(pshape);
  }
}

void ModelSession::loadWeights(const std::vector<std::string> &paths) {
  if (paths.size() < 2u)
    throw std::runtime_error("[BuddyRuntime] Expected 2 weight file(s), got " +
                             std::to_string(paths.size()));

  {
    intptr_t shape[1] = {BUDDY_DSR1_PARAMS_SIZE_F16_PARAMS};
    f16_params_ = std::make_unique<MemRef<uint16_t, 1>>(shape);
    std::ifstream f(paths[0], std::ios::binary);
    if (!f)
      throw std::runtime_error("[BuddyRuntime] Cannot open weights: " +
                               paths[0]);
    f.read(reinterpret_cast<char *>(f16_params_->getData()),
           sizeof(uint16_t) * f16_params_->getSize());
    if (f.fail())
      throw std::runtime_error("[BuddyRuntime] Read failed: " + paths[0]);
  }
  {
    intptr_t shape[1] = {BUDDY_DSR1_PARAMS_SIZE_I8_PARAMS};
    i8_params_ = std::make_unique<MemRef<int8_t, 1>>(shape);
    std::ifstream f(paths[1], std::ios::binary);
    if (!f)
      throw std::runtime_error("[BuddyRuntime] Cannot open weights: " +
                               paths[1]);
    f.read(reinterpret_cast<char *>(i8_params_->getData()),
           sizeof(int8_t) * i8_params_->getSize());
    if (f.fail())
      throw std::runtime_error("[BuddyRuntime] Read failed: " + paths[1]);
  }
}

void ModelSession::prefill(Text<size_t, 2> &tokens) {
  impl_->prefillFn(&impl_->abi, f16_params_.get(), i8_params_.get(), &tokens);
  int tokenCount = (int)tokens.getTokenCnt();
  position_ = tokenCount;
}

void ModelSession::decode(int tokenId) {
  decodeTokenInput_->getData()[0] = (long long)tokenId;
  cachePosition_->getData()[0] = (long long)position_;

  auto &a = impl_->abi;
  impl_->decodeFn(
      &a, f16_params_.get(), i8_params_.get(), decodeTokenInput_.get(),
      cachePosition_.get(), &a.kv(0), &a.kv(1), &a.kv(2), &a.kv(3), &a.kv(4),
      &a.kv(5), &a.kv(6), &a.kv(7), &a.kv(8), &a.kv(9), &a.kv(10), &a.kv(11),
      &a.kv(12), &a.kv(13), &a.kv(14), &a.kv(15), &a.kv(16), &a.kv(17),
      &a.kv(18), &a.kv(19), &a.kv(20), &a.kv(21), &a.kv(22), &a.kv(23),
      &a.kv(24), &a.kv(25), &a.kv(26), &a.kv(27), &a.kv(28), &a.kv(29),
      &a.kv(30), &a.kv(31), &a.kv(32), &a.kv(33), &a.kv(34), &a.kv(35),
      &a.kv(36), &a.kv(37), &a.kv(38), &a.kv(39), &a.kv(40), &a.kv(41),
      &a.kv(42), &a.kv(43), &a.kv(44), &a.kv(45), &a.kv(46), &a.kv(47),
      &a.kv(48), &a.kv(49), &a.kv(50), &a.kv(51), &a.kv(52), &a.kv(53),
      &a.kv(54), &a.kv(55));

  position_ += 1;
}

void ModelSession::resetPosition() { position_ = 0; }

bool ModelSession::handleKVCacheOverflow(int keepTokenNum, float ropeTheta) {
  if (position_ < cfg_.maxTokenLen)
    return false;

  const int currentTokens = std::min(position_, cfg_.maxTokenLen);
  keepTokenNum = std::clamp(keepTokenNum, 0, currentTokens - 1);
  const int discardLen = std::max(1, (currentTokens - keepTokenNum) / 2);

  uint16_t *rawPtrs[BUDDY_DSR1_KV_LAYERS];
  for (int i = 0; i < cfg_.kvLayers; ++i)
    rawPtrs[i] = impl_->abi.kv(i).getData();

  buddy::kvcache::discardKVCache(rawPtrs, cfg_.kvLayers, cfg_.headNum,
                                 cfg_.maxTokenLen, cfg_.hiddenSize,
                                 keepTokenNum, discardLen, currentTokens);

  auto inverseFreqs =
      buddy::kvcache::buildInverseRopeFreqs(ropeTheta, cfg_.hiddenSize);
  buddy::kvcache::adjustKeyCacheRope(
      rawPtrs, cfg_.kvLayers, cfg_.headNum, cfg_.maxTokenLen, cfg_.hiddenSize,
      keepTokenNum, discardLen, currentTokens, inverseFreqs);

  position_ = std::clamp(currentTokens - discardLen, 0, cfg_.maxTokenLen);
  return true;
}

const float *ModelSession::logitsData(int tokenOffset) const {
  const int n = cfg_.vocabSize;
  if ((int)logitsFloat_.size() != n)
    logitsFloat_.resize(n);
  const uint16_t *raw = impl_->abi.logits().getData() + (size_t)tokenOffset * n;
  for (int i = 0; i < n; ++i)
    logitsFloat_[i] = halfToFloat(raw[i]);
  return logitsFloat_.data();
}

std::string ModelSession::loadedSoPath() const { return cfg_.modelSoPath; }

std::unique_ptr<ModelSession>
ModelSession::createFromRax(const std::string &raxPath,
                            ModelManifest &resolvedManifest) {
  resolvedManifest = ModelManifest::loadFromRax(raxPath);
  Config cfg;
  cfg.modelSoPath = resolvedManifest.soPath;
  return create(cfg);
}

} // namespace runtime
} // namespace buddy
