from .graph.op_def import *
torch_ops_map = {
    "output": OutputOp,
    "placeholder": PlaceholderOp,
    "arange.start": ArangeOp,
    "arange.default": ArangeOp,
    "unsqueeze.default": UnsqueezeOp,
    "view.default": ViewOp,
    "ones.default": OnesOp,
    "full.default": FullOp,
    "lt.Tensor": LessthanOp,
    "embedding.default": EmbeddingOp,
    "masked_fill.Scalar": MaskedFillOp,
    "slice.Tensor": SliceOp,
    "expand.default": ExpandOp,
    "_to_copy.default": ToCopyOp,
    "rsub.Scalar": RsubOp,
    "pow.Tensor_Scalar": PowOp,
    "mean.dim": MeanOp,
    "rsqrt.default": RsqrtOp,
    "mul.Tensor": MulOp,
    "t.default": TransposeOp,
    "mm.default": MatmulOp,
    "transpose.int": TransposeSpecificDimOp,
    "index.Tensor": IndexOp,
    "neg.default": NegOp,
    "cat.default": CatOp,
    "squeeze.dim": SqueezeOp,
    "bmm.default": BatchMatmulOp,
    "div.Tensor": DivOp,
    "_softmax.default": SoftmaxOp,
    "clone.default": CloneOp,
    "silu.default": SiluOp,
}