#!/usr/bin/env python3
"""Emit the model's parameter buffer as a DDR segment plus the load plan.

The compiled graph reads its parameters as one flat FP32 buffer whose offsets
the compiler itself resolved (``validation/weight-layout.json``). This tool
materialises exactly that buffer from the checkpoint and writes it as a file the
board's multi-segment loader can place at a fixed DDR address, together with the
TOML plan and a SHA256 the loader re-verifies.

The image itself does not contain these bytes: the model's ``main`` declares the
buffer in the linker's NOLOAD ``.workspace`` section and only exports a
descriptor pointing at it. That is what keeps the uploaded image ~108 KB while
the parameters arrive as their own 653 MiB segment.

Only FP32 is emitted here. W8A8 is the deployment target for the full model
(``validation/weight-image.json``), but this segment matches what the current
compiled graph actually reads, so a board run can be compared directly against
the FP32 host reference.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))


def rotary_inv_freq(head_dim, theta):
    index = np.arange(0, head_dim, 2, dtype=np.float64)
    return (1.0 / (theta ** (index / head_dim))).astype(np.float32)


def read_tensor_f32(handle, base, entry, count):
    handle.seek(base + entry["data_offsets"][0])
    if entry["dtype"] == "BF16":
        raw = np.frombuffer(handle.read(count * 2), dtype=np.uint16)
        return (raw.astype(np.uint32) << 16).view(np.float32)
    if entry["dtype"] == "F32":
        return np.frombuffer(handle.read(count * 4), dtype=np.float32)
    raise ValueError(f"unsupported checkpoint dtype {entry['dtype']}")


def build(layout_path, checkpoint, config_path, output, name,
          address, layers, head_dim, kv_heads, cache_len):
    layout = json.loads(Path(layout_path).read_text())
    if layout["status"] != "PASS":
        raise SystemExit("weight layout is not PASS")
    config = json.loads(Path(config_path).read_text())
    parameters = config.get("rope_parameters") or {}
    theta = parameters.get("rope_theta", config.get("rope_theta", 10000.0))

    with open(checkpoint, "rb") as handle:
        header_length = struct.unpack("<Q", handle.read(8))[0]
        header = json.loads(handle.read(header_length))
        header.pop("__metadata__", None)
        base = 8 + header_length

        total = layout["weight_buffer_elements"]
        buffer = np.zeros(total, dtype=np.float32)
        computed = []
        with open(checkpoint, "rb") as tensor_handle:
            for section in layout["sections"]:
                tensor = section["checkpoint_tensor"]
                offset = section["offset_elements"]
                count = section["elements"]
                if tensor is None:
                    values = rotary_inv_freq(head_dim, theta)
                    if values.size != count:
                        raise ValueError("rotary table size mismatch")
                    buffer[offset:offset + count] = values
                    computed.append(section["index"])
                    continue
                values = read_tensor_f32(tensor_handle, base, header[tensor], count)
                buffer[offset:offset + count] = values

    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    segment = output / name
    segment.write_bytes(buffer.tobytes())
    digest = hashlib.sha256(segment.read_bytes()).hexdigest()

    return {
        "segment": str(segment),
        "bytes": segment.stat().st_size,
        "sha256": digest,
        "address": hex(address),
        "address_value": address,
        "elements": int(buffer.size),
        "sections": len(layout["sections"]),
        "computed_sections": computed,
        "layout_sha256": layout["layout_sha256"],
        "dtype": "f32",
        "source_layout": str(layout_path),
    }


def plan_text(model_file, model_size, model_sha, weights_file, weights_size,
              weights_sha, weights_address, model_address=0x80000000):
    return "\n".join([
        "# Generated by model/tools/build_nr_weight_segment.py -- do not edit.",
        "# The board loader validates every field and re-hashes each segment.",
        "version = 1",
        f"ddr_base = 0x{0x80000000:08x}",
        f"ddr_size = 0x{0x400000000:x}",
        "alignment = 64",
        "",
        "[[segments]]",
        'name = "model"',
        f'file = "{model_file}"',
        f"address = 0x{model_address:08x}",
        f"size = {model_size}",
        f'sha256 = "{model_sha}"',
        "",
        "[[segments]]",
        'name = "weights"',
        f'file = "{weights_file}"',
        f"address = 0x{weights_address:08x}",
        f"size = {weights_size}",
        f'sha256 = "{weights_sha}"',
        "",
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", type=Path, required=True)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--image", type=Path, required=True,
                        help="the model .bin the plan's first segment points at")
    parser.add_argument("--address", type=lambda v: int(v, 0), default=0xB8000000)
    parser.add_argument("--layers", type=int, default=1)
    parser.add_argument("--head-dim", type=int, default=128)
    parser.add_argument("--kv-heads", type=int, default=8)
    parser.add_argument("--cache-len", type=int, default=512)
    parser.add_argument("--name", default="weights-fp32.bin")
    args = parser.parse_args()

    record = build(args.layout, args.checkpoint, args.config, args.output,
                   args.name, args.address, args.layers, args.head_dim,
                   args.kv_heads, args.cache_len)

    image = args.image.resolve()
    image_size = image.stat().st_size
    if image_size % 64:
        raise SystemExit(f"model image size {image_size} is not a 64-byte multiple; "
                         "pad it before building the plan")
    image_sha = hashlib.sha256(image.read_bytes()).hexdigest()
    segment = Path(record["segment"]).resolve()
    if record["bytes"] % 64 or record["address_value"] % 64:
        raise SystemExit("segment size and address must be 64-byte multiples")
    # The plan references segments by relative path, so both files must share a
    # directory.
    if segment.parent != image.parent:
        raise SystemExit("the model image and the weight segment must be in the same "
                         f"directory for the plan: {image.parent} vs {segment.parent}")

    plan = args.output / "ddr-load.plan"
    plan.write_text(plan_text(image.name, image_size, image_sha, segment.name,
                              record["bytes"], record["sha256"],
                              record["address_value"]))
    record["plan"] = str(plan)
    record["model_segment"] = {"file": image.name, "bytes": image_size,
                               "sha256": image_sha, "address": hex(0x80000000)}
    record["total_ddr_bytes"] = image_size + record["bytes"]
    (args.output / "weight-segment.json").write_text(json.dumps(record, indent=2) + "\n")
    print(json.dumps(record, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())