/* Generated by cases.py; independent direct NCHW/OIHW dense Conv2D oracle. */
#include "support.h"
#ifdef HOST_TEST
#include <stdio.h>
#endif
#define CIN 3
#define COUT 16
#define H 224
#define W 224
#define KH 3
#define KW 3
#define SH 2
#define SW 2
#define PH 1
#define PW 1
#define OH 112
#define OW 112
#define K (CIN * KH * KW)
#define INPUT_COUNT (CIN * H * W)
#define WEIGHT_COUNT (COUT * K)
#define OUTPUT_COUNT (COUT * OH * OW)
#define TRIALS 12
#ifndef HOST_TEST
static float x_storage[INPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float weight_storage[WEIGHT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float bias_storage[COUT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[OUTPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define weight_storage NULL
#define bias_storage NULL
#define out_storage NULL
#endif
extern void run_conv_stem(float *, float *, float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int ic, int h, int w, int trial) {
  if (trial == 0) return ic % 2 ? -0.0f : 0.0f;
  if (trial == 1) return (ic + 1) * 0.017f + h * 0.0031f - w * 0.0019f;
  if (trial == 2) return ic == 0 ? 0.25f + h * 0.001f + w * 0.003f : 0.0f;
  if (trial == 3) return ic == CIN - 1 ? -0.5f + h * 0.002f - w * 0.007f : 0.0f;
  if (trial == 6) {
    float scale = (float)(ic + 1) * 0.03125f;
    if (h == 0 && w == 0) return scale;
    if (h == 0 && w == W - 1) return -2 * scale;
    if (h == H - 1 && w == 0) return 3 * scale;
    if (h == H - 1 && w == W - 1) return -4 * scale;
    return 0.0f;
  }
  if (trial == 7) return ((ic + h + w) % 2 ? -0.25f : 0.25f) + (h % 7) * 0.0001f;
  if (trial == 9) return 1.0f;
  if (trial == 10)
    return (h == 0 || w == 0 || h == H - 1 || w == W - 1) ? (ic + 1) * 0.125f : 0.0f;
  return (float)((ic * 17 + h * 37 + w * 13 + trial * 11) % 251 - 125) * 0.009f;
}

static float weight_value(int oc, int ic, int kh, int kw, int trial) {
  int k = (ic * KH + kh) * KW + kw;
  /* Across trials 4/5 and output channels, cover every one of the 27 taps. */
  if (trial == 4 || trial == 5)
    return k == (oc + (trial - 4) * COUT) % K ? (oc % 2 ? -0.5f : 0.25f) : 0.0f;
  if (trial == 7) return 0.75f + ((oc * 3 + k * 7) % 13) * 0.0001f;
  if (trial == 8 && oc != COUT - 1) return 0.0f;
  if (trial == 9) return 1.0f;
  return (float)((oc * 31 + ic * 19 + kh * 7 + kw * 11 + trial * 3) % 97 - 48) * 0.013f;
}

static float bias_value(int oc, int trial) {
  if (trial == 8) return oc == COUT - 1 ? -0.25f : 0.0f;
  if (trial == 9) return 0.0f;
  return (float)((oc * 13 + trial * 5) % 97 - 48) * 0.011f;
}

int launch(void) {
  GuardedBuffer buffers[4] = {{0}};
  const size_t sizes[4] = {INPUT_COUNT, WEIGHT_COUNT, COUT, OUTPUT_COUNT};
  float *storage[4] = {x_storage, weight_storage, bias_storage, out_storage};
  for (int i = 0; i < 4; ++i) {
    if (buffer_init(&buffers[i], sizes[i], storage[i])) {
      for (int j = 0; j < i; ++j) buffer_free(&buffers[j]);
      return report_check("conv_stem_cin3_cout16_h224_k3_s2_p1", 1, 0);
    }
  }
  float *x = buffers[0].data, *weight = buffers[1].data;
  float *bias = buffers[2].data, *out = buffers[3].data;
  unsigned errors = 0;
  double maximum = 0, maximum_ratio = 0, maximum_bound = 0;
  const double ku = (K + 2) * 0x1p-24;
  const double gamma = ku / (1.0 - ku);
  for (int trial = 0; trial < TRIALS; ++trial) {
    for (int ic = 0; ic < CIN; ++ic)
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w) x[(ic * H + h) * W + w] = x_value(ic, h, w, trial);
    for (int oc = 0; oc < COUT; ++oc) {
      bias[oc] = bias_value(oc, trial);
      for (int ic = 0; ic < CIN; ++ic)
        for (int kh = 0; kh < KH; ++kh)
          for (int kw = 0; kw < KW; ++kw)
            weight[((oc * CIN + ic) * KH + kh) * KW + kw] = weight_value(oc, ic, kh, kw, trial);
    }
    for (int i = 0; i < OUTPUT_COUNT; ++i) out[i] = -9999.0f;
    run_conv_stem(x, weight, bias, out);
    /* Batch is fixed to 1: the remaining six loops are direct Conv2D.
     * Skip out-of-bounds pixels (zero padding), never flatten input to [M,K]. */
    for (int oc = 0; oc < COUT; ++oc)
      for (int oh = 0; oh < OH; ++oh)
        for (int ow = 0; ow < OW; ++ow) {
          double sum = 0, magnitude = 0;
          for (int ic = 0; ic < CIN; ++ic)
            for (int kh = 0; kh < KH; ++kh)
              for (int kw = 0; kw < KW; ++kw) {
                int ih = oh * SH + kh - PH, iw = ow * SW + kw - PW;
                if (ih < 0 || ih >= H || iw < 0 || iw >= W) continue;
                double product = (double)x[(ic * H + ih) * W + iw] *
                    (double)weight[((oc * CIN + ic) * KH + kh) * KW + kw];
                sum += product;
                magnitude += product < 0 ? -product : product;
              }
          sum += (double)bias[oc];
          magnitude += bias[oc] < 0 ? -(double)bias[oc] : (double)bias[oc];
          double bound = gamma * magnitude + (K + 2) * 0x1p-149;
          if (bound > maximum_bound) maximum_bound = bound;
          float actual = out[(oc * OH + oh) * OW + ow];
          if (!__builtin_isfinite(actual)) {
            ++errors; maximum = __builtin_inf(); maximum_ratio = __builtin_inf();
          } else {
            double difference = (double)actual - sum;
            if (difference < 0) difference = -difference;
            errors += difference > bound;
            if (difference > maximum) maximum = difference;
            double ratio = difference / bound;
            if (ratio > maximum_ratio) maximum_ratio = ratio;
          }
        }
    for (int ic = 0; ic < CIN; ++ic)
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w)
          errors += float_bits(x[(ic * H + h) * W + w]) != float_bits(x_value(ic, h, w, trial));
    for (int oc = 0; oc < COUT; ++oc) {
      errors += float_bits(bias[oc]) != float_bits(bias_value(oc, trial));
      for (int ic = 0; ic < CIN; ++ic)
        for (int kh = 0; kh < KH; ++kh)
          for (int kw = 0; kw < KW; ++kw)
            errors += float_bits(weight[((oc * CIN + ic) * KH + kh) * KW + kw]) !=
                float_bits(weight_value(oc, ic, kh, kw, trial));
    }
    for (int i = 0; i < 4; ++i) errors += buffer_check(&buffers[i]);
  }
  for (int i = 0; i < 4; ++i) buffer_free(&buffers[i]);
#ifdef HOST_TEST
  printf("conv_stem metrics max_abs_error=%.17g max_error_over_bound=%.17g max_bound=%.17g\n",
         maximum, maximum_ratio, maximum_bound);
#endif
  return report_check("conv_stem_cin3_cout16_h224_k3_s2_p1", errors, (float)maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
