/* Generated by triton/cases.py; independent NCHW channel-broadcast oracle. */
#include "support.h"
#define CHANNELS 120
#define HEIGHT 14
#define WIDTH 14
#define COUNT 23520
#define BLOCK 128
#ifndef HOST_TEST
static float x_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float scale_storage[CHANNELS + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define scale_storage NULL
#define out_storage NULL
#endif
static float reference[COUNT] WORKSPACE;
extern void run_se_mul(float *, float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float scale_value(int c, int trial) {
  /* Unique per-channel scales expose a wrong channel stride or NHWC index. */
  if (trial == 0) return (float)(c + 1) * 0.0009765625f;
  if (trial == 1) return (float)(CHANNELS - c) * 0.0009765625f;
  if (trial == 3) return c == CHANNELS - 1 ? 1.0f : 0.0f;
  switch (c % 8) {
    case 0: return 0.0f;
    case 1: return -0.0f;
    case 2: return 1.0f;
    case 3: return -1.0f;
    default: return (float)(c + 1) * (c % 2 ? -0.00390625f : 0.00390625f);
  }
}

static float x_value(int c, int h, int w, int trial) {
  if (trial == 0) return 1.0f;
  if (trial == 2 && h == 0 && w == 0) return c % 2 ? -0.0f : 0.0f;
  return (float)((c * 17 + h * 11 + w * 5 + trial * 7) % 257 - 128) * 0.125f + 0.0625f;
}

int launch(void) {
  GuardedBuffer x = {0}, scale = {0}, out = {0};
  if (buffer_init(&x, COUNT, x_storage)) return report_check("se_mul_c120_h14_w14", 1, 0);
  /* Scale has exactly CHANNELS accessible elements, never COUNT. */
  if (buffer_init(&scale, CHANNELS, scale_storage)) {
    buffer_free(&x); return report_check("se_mul_c120_h14_w14", 1, 0);
  }
  if (buffer_init(&out, COUNT, out_storage)) {
    buffer_free(&x); buffer_free(&scale); return report_check("se_mul_c120_h14_w14", 1, 0);
  }
  unsigned errors = 0;
  float maximum = 0;
  for (int trial = 0; trial < 4; ++trial) {
    for (int c = 0; c < CHANNELS; ++c) {
      scale.data[c] = scale_value(c, trial);
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w) {
          int index = (c * HEIGHT + h) * WIDTH + w;
          x.data[index] = x_value(c, h, w, trial);
          out.data[index] = -9999.0f;
        }
    }
    /* Independent reference: explicit NCHW loops and channel broadcasting.
     * Compute before launch so corrupted inputs cannot hide a kernel error. */
    for (int c = 0; c < CHANNELS; ++c)
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w) {
          int index = (c * HEIGHT + h) * WIDTH + w;
          reference[index] = x.data[index] * scale.data[c];
        }
    run_se_mul(x.data, scale.data, out.data);
    for (int c = 0; c < CHANNELS; ++c) {
      errors += float_bits(scale.data[c]) != float_bits(scale_value(c, trial));
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w) {
          int index = (c * HEIGHT + h) * WIDTH + w;
          if (!__builtin_isfinite(out.data[index])) {
            ++errors; maximum = __builtin_inff();
          } else {
            /* Exact FP32 numerical equality accepts either zero sign. */
            errors += out.data[index] != reference[index];
            float difference = out.data[index] - reference[index];
            if (difference < 0) difference = -difference;
            if (difference > maximum) maximum = difference;
          }
          errors += float_bits(x.data[index]) != float_bits(x_value(c, h, w, trial));
        }
    }
    errors += buffer_check(&x) + buffer_check(&scale) + buffer_check(&out);
  }
  buffer_free(&x); buffer_free(&scale); buffer_free(&out);
  return report_check("se_mul_c120_h14_w14", errors, maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
