/* Generated by cases.py; independent double NCHW/OIHW depthwise oracle. */
#include "support.h"
#ifdef HOST_TEST
#include <stdio.h>
#endif
#define C 144
#define H 14
#define W 14
#define KH 5
#define KW 5
#define SH 1
#define SW 1
#define PH 2
#define PW 2
#define OH 14
#define OW 14
#define INPUT_COUNT (C * H * W)
#define WEIGHT_COUNT (C * KH * KW)
#define OUTPUT_COUNT (C * OH * OW)
#define TRIALS 8
#ifndef HOST_TEST
static float x_storage[INPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float weight_storage[WEIGHT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float bias_storage[C + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[OUTPUT_COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define weight_storage NULL
#define bias_storage NULL
#define out_storage NULL
#endif
extern void run_depthwise_conv2d(float *, float *, float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int c, int h, int w, int trial) {
  if (trial == 0) return w % 2 ? -0.0f : 0.0f;
  if (trial == 1) return (float)(c + 1) * 0.007f + h * 0.013f - w * 0.009f;
  if (trial == 2) {
    float scale = (float)(c + 1) * 0.125f;
    if (h == 0 && w == 0) return scale;
    if (h == 0 && w == W - 1) return -2 * scale;
    if (h == H - 1 && w == 0) return 3 * scale;
    if (h == H - 1 && w == W - 1) return -4 * scale;
    return 0.0f;
  }
  if (trial == 3 && c != C - 1) return 0.0f;
  if (trial == 6) return (h + w) % 2 ? -1.0f : 1.0f;
  return (float)((c * 17 + h * 37 + w * 13 + trial * 11) % 251 - 125) * 0.011f;
}

static float weight_value(int c, int kh, int kw, int trial) {
  if (trial == 4) return kh == 0 && kw == KW - 1 ? (float)(c + 1) * 0.03125f : 0.0f;
  if (trial == 5) return kh == KH - 1 && kw == 0 ? (float)(c + 1) * -0.0625f : 0.0f;
  if (trial == 6) return 0.25f + (float)((c + kh * 3 + kw * 7) % 13) * 0.0001f;
  return (float)((c * 31 + kh * 7 + kw * 19 + trial * 3) % 97 - 48) * 0.017f;
}

static float bias_value(int c, int trial) {
  if (trial == 3) return c == C - 1 ? -0.25f : 0.0f;
  return (float)((c * 5 + trial * 7) % 37 - 18) * 0.013f;
}

int launch(void) {
  GuardedBuffer buffers[4] = {{0}};
  const size_t sizes[4] = {INPUT_COUNT, WEIGHT_COUNT, C, OUTPUT_COUNT};
  float *storage[4] = {x_storage, weight_storage, bias_storage, out_storage};
  for (int i = 0; i < 4; ++i) {
    if (buffer_init(&buffers[i], sizes[i], storage[i])) {
      for (int j = 0; j < i; ++j) buffer_free(&buffers[j]);
      return report_check("dwconv_c144_h14_k5_s1_p2", 1, 0);
    }
  }
  float *x = buffers[0].data, *weight = buffers[1].data;
  float *bias = buffers[2].data, *out = buffers[3].data;
  unsigned errors = 0;
  double maximum = 0, maximum_ratio = 0, maximum_bound = 0;
  const double ku = (KH * KW + 2) * 0x1p-24;
  const double gamma = ku / (1.0 - ku);
  for (int trial = 0; trial < TRIALS; ++trial) {
    for (int c = 0; c < C; ++c) {
      bias[c] = bias_value(c, trial);
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w) x[(c * H + h) * W + w] = x_value(c, h, w, trial);
      for (int kh = 0; kh < KH; ++kh)
        for (int kw = 0; kw < KW; ++kw)
          weight[(c * KH + kh) * KW + kw] = weight_value(c, kh, kw, trial);
    }
    for (int i = 0; i < OUTPUT_COUNT; ++i) out[i] = -9999.0f;
    run_depthwise_conv2d(x, weight, bias, out);
    /* Independent c/oh/ow/kh/kw loops. Padding is skipped, not flattened
     * into the previous/next input row or channel. No im2col or GEMM. */
    for (int c = 0; c < C; ++c)
      for (int oh = 0; oh < OH; ++oh)
        for (int ow = 0; ow < OW; ++ow) {
          double sum = 0, magnitude = 0;
          for (int kh = 0; kh < KH; ++kh) {
            int ih = oh * SH + kh - PH;
            if (ih < 0 || ih >= H) continue;
            for (int kw = 0; kw < KW; ++kw) {
              int iw = ow * SW + kw - PW;
              if (iw < 0 || iw >= W) continue;
              double product = (double)x[(c * H + ih) * W + iw] *
                               (double)weight[(c * KH + kh) * KW + kw];
              sum += product;
              magnitude += product < 0 ? -product : product;
            }
          }
          sum += (double)bias[c];
          magnitude += bias[c] < 0 ? -(double)bias[c] : (double)bias[c];
          double bound = gamma * magnitude + (KH * KW + 2) * 0x1p-149;
          if (bound > maximum_bound) maximum_bound = bound;
          float actual = out[(c * OH + oh) * OW + ow];
          if (!__builtin_isfinite(actual)) {
            ++errors; maximum = __builtin_inf(); maximum_ratio = __builtin_inf();
          } else {
            double difference = (double)actual - sum;
            if (difference < 0) difference = -difference;
            errors += difference > bound;
            if (difference > maximum) maximum = difference;
            double ratio = difference / bound;
            if (ratio > maximum_ratio) maximum_ratio = ratio;
          }
        }
    for (int c = 0; c < C; ++c) {
      errors += float_bits(bias[c]) != float_bits(bias_value(c, trial));
      for (int h = 0; h < H; ++h)
        for (int w = 0; w < W; ++w)
          errors += float_bits(x[(c * H + h) * W + w]) != float_bits(x_value(c, h, w, trial));
      for (int kh = 0; kh < KH; ++kh)
        for (int kw = 0; kw < KW; ++kw)
          errors += float_bits(weight[(c * KH + kh) * KW + kw]) !=
                    float_bits(weight_value(c, kh, kw, trial));
    }
    for (int i = 0; i < 4; ++i) errors += buffer_check(&buffers[i]);
  }
  for (int i = 0; i < 4; ++i) buffer_free(&buffers[i]);
#ifdef HOST_TEST
  printf("depthwise_conv2d metrics max_abs_error=%.17g max_error_over_bound=%.17g max_bound=%.17g\n",
         maximum, maximum_ratio, maximum_bound);
#endif
  return report_check("dwconv_c144_h14_k5_s1_p2", errors, (float)maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
