/**
 * Runtime test for fp16 matmul with boundary handling.
 *
 * Verifies correctness of linalg.matmul (f16) -> IME lowering for matrices
 * with dimensions not aligned to the fp16 IME tile size (TILE_M=4, TILE_K=4,
 * TILE_N=4).
 *
 * Test case: C[7x5] = A[7x6] * B[6x5]
 *   M=7: 1 full tile (4) + 3 remaining
 *   K=6: 1 full tile (4) + 2 remaining
 *   N=5: 1 full tile (4) + 1 remaining
 *
 * Compile with:
 *   buddy-llc -mattr=+m,+v,+zvfh,+buddyext  linalg-to-ime-matmul-fp16-boundary-func.ll
 *   riscv64-unknown-linux-gnu-gcc runtime_matmul_fp16_boundary.c \
 *       linalg-to-ime-matmul-fp16-boundary-func.s -o matmul_fp16_boundary
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Use compiler's _Float16 support (GCC 12+ / Clang 6+) */
typedef _Float16 float16_t;

/* Matrix dimensions */
#define M 7
#define K 6
#define N 5

/* Input matrices in fp16 */
float16_t A[M][K] = {
    {1.0f16, 2.0f16, 3.0f16, 4.0f16, 5.0f16, 6.0f16},
    {1.0f16, 1.0f16, 1.0f16, 1.0f16, 1.0f16, 1.0f16},
    {2.0f16, 2.0f16, 2.0f16, 2.0f16, 2.0f16, 2.0f16},
    {3.0f16, 3.0f16, 3.0f16, 3.0f16, 3.0f16, 3.0f16},
    {4.0f16, 4.0f16, 4.0f16, 4.0f16, 4.0f16, 4.0f16},
    {5.0f16, 5.0f16, 5.0f16, 5.0f16, 5.0f16, 5.0f16},
    {1.0f16, 2.0f16, 3.0f16, 4.0f16, 5.0f16, 6.0f16},
};

float16_t B[K][N] = {
    {1.0f16, 0.0f16, 0.0f16, 0.0f16, 0.0f16},
    {0.0f16, 1.0f16, 0.0f16, 0.0f16, 0.0f16},
    {0.0f16, 0.0f16, 1.0f16, 0.0f16, 0.0f16},
    {0.0f16, 0.0f16, 0.0f16, 1.0f16, 0.0f16},
    {0.0f16, 0.0f16, 0.0f16, 0.0f16, 1.0f16},
    {1.0f16, 1.0f16, 1.0f16, 1.0f16, 1.0f16},
};

/* Output matrix (zeroed before call) */
float16_t C[M][N];
float16_t C_expected[M][N];

/*
 * External function generated by buddy-opt + buddy-llc.
 * MLIR memref ABI: each memref<MxNxf16> expands to
 *   (allocated*, aligned*, offset, size0, size1, stride0, stride1)
 */
extern void matmul_fp16_boundary(
    float16_t *A_alloc, float16_t *A_aligned, int64_t A_off,
    int64_t A_s0, int64_t A_s1, int64_t A_t0, int64_t A_t1,
    float16_t *B_alloc, float16_t *B_aligned, int64_t B_off,
    int64_t B_s0, int64_t B_s1, int64_t B_t0, int64_t B_t1,
    float16_t *C_alloc, float16_t *C_aligned, int64_t C_off,
    int64_t C_s0, int64_t C_s1, int64_t C_t0, int64_t C_t1);

/* Reference matmul in float to avoid fp16 accumulation error */
static void reference_matmul(void) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            float acc = 0.0f;
            for (int k = 0; k < K; k++)
                acc += (float)A[i][k] * (float)B[k][j];
            C_expected[i][j] = (_Float16)acc;
        }
    }
}

static void print_matrix_f16(const char *name, float16_t *mat, int rows, int cols) {
    printf("%s [%dx%d]:\n", name, rows, cols);
    for (int i = 0; i < rows; i++) {
        printf("  [");
        for (int j = 0; j < cols; j++) {
            printf("%8.3f", (float)mat[i * cols + j]);
            if (j < cols - 1) printf(", ");
        }
        printf("]\n");
    }
}

/* Allow a small relative tolerance for fp16 arithmetic */
static int fp16_near(float16_t a, float16_t b) {
    float fa = (float)a, fb = (float)b;
    float diff = fa - fb;
    if (diff < 0) diff = -diff;
    float ref = fb < 0 ? -fb : fb;
    if (ref < 1e-3f) ref = 1e-3f;
    return diff / ref < 1e-2f; /* 1 % relative tolerance */
}

static int verify_result(void) {
    int errors = 0;
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            if (!fp16_near(C[i][j], C_expected[i][j])) {
                printf("ERROR at C[%d][%d]: got %.4f, expected %.4f\n",
                       i, j, (float)C[i][j], (float)C_expected[i][j]);
                errors++;
            }
        }
    }
    return errors;
}

int main(void) {
    printf("=== FP16 Matmul Boundary Test ===\n");
    printf("A[%dx%d] * B[%dx%d] = C[%dx%d]\n", M, K, K, N, M, N);
    printf("FP16 IME tile sizes: TILE_M=4, TILE_K=4, TILE_N=4\n");
    printf("  M=%d: %d full tile(s) + %d remaining\n", M, M/4, M%4);
    printf("  K=%d: %d full tile(s) + %d remaining\n", K, K/4, K%4);
    printf("  N=%d: %d full tile(s) + %d remaining\n\n", N, N/4, N%4);

    memset(C, 0, sizeof(C));
    reference_matmul();

    /* Call IME-lowered function with unpacked memref descriptors */
    matmul_fp16_boundary(
        (float16_t*)A, (float16_t*)A, 0, M, K, K, 1,
        (float16_t*)B, (float16_t*)B, 0, K, N, N, 1,
        (float16_t*)C, (float16_t*)C, 0, M, N, N, 1);

    print_matrix_f16("A", (float16_t*)A, M, K);
    print_matrix_f16("B", (float16_t*)B, K, N);
    print_matrix_f16("C (IME result)", (float16_t*)C, M, N);
    print_matrix_f16("C (reference) ", (float16_t*)C_expected, M, N);

    int errors = verify_result();
    if (errors == 0)
        printf("\nPASS: all %d elements match.\n", M * N);
    else
        printf("\nFAIL: %d element(s) differ.\n", errors);

    return errors != 0;
}
