/* Generated by triton/cases.py. Independent C oracle; no Triton reference. */
#include "support.h"
#define COUNT 4704
#define BLOCK 128
#ifndef HOST_TEST
static float x_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float y_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define y_storage NULL
#define out_storage NULL
#endif
static float reference[COUNT] WORKSPACE;
extern void run_add(float *, float *, float *);

static float x_value(int i, int trial) {
  return (float)((i * 17 + trial * 13) % 257 - 128) * 0.125f + 0.0625f;
}
static float y_value(int i, int trial) {
  return (float)((i * 29 + trial * 7) % 127 - 63) * 0.0625f + 0.03125f;
}

int launch(void) {
  GuardedBuffer x = {0}, y = {0}, out = {0};
  if (buffer_init(&x, COUNT, x_storage)) return report_check("add_count4704", 1, 0);
  if (buffer_init(&y, COUNT, y_storage)) {
    buffer_free(&x); return report_check("add_count4704", 1, 0);
  }
  if (buffer_init(&out, COUNT, out_storage)) {
    buffer_free(&x); buffer_free(&y); return report_check("add_count4704", 1, 0);
  }
  unsigned errors = 0;
  float maximum = 0;
  for (int trial = 0; trial < 2; ++trial) {
    for (int i = 0; i < COUNT; ++i) {
      x.data[i] = x_value(i, trial);
      y.data[i] = y_value(i, trial);
      out.data[i] = -9999.0f;
    }
    /* Compute before the call; corruption of inputs cannot hide an error. */
    for (int i = 0; i < COUNT; ++i)
      reference[i] = x.data[i] + y.data[i];
    run_add(x.data, y.data, out.data);
    for (int i = 0; i < COUNT; ++i) {
      float difference = out.data[i] - reference[i];
      if (difference < 0) difference = -difference;
      if (!__builtin_isfinite(out.data[i])) {
        ++errors; maximum = __builtin_inff();
      } else {
        errors += out.data[i] != reference[i];
        if (difference > maximum) maximum = difference;
      }
      errors += x.data[i] != x_value(i, trial);
      errors += y.data[i] != y_value(i, trial);
    }
    errors += buffer_check(&x) + buffer_check(&y) + buffer_check(&out);
  }
  buffer_free(&x); buffer_free(&y); buffer_free(&out);
  return report_check("add_count4704", errors, maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
