/* Generated by triton/cases.py; independent double NCHW spatial-mean oracle. */
#include "support.h"
#ifdef HOST_TEST
#include <stdio.h>
#endif
#define CHANNELS 576
#define HEIGHT 7
#define WIDTH 7
#define SPATIAL (HEIGHT * WIDTH)
#define COUNT 28224
#define BLOCK 64
#define TRIALS 7
#ifndef HOST_TEST
static float x_storage[COUNT + 2 * GUARD_FLOATS] WORKSPACE;
static float out_storage[CHANNELS + 2 * GUARD_FLOATS] WORKSPACE;
#else
#define x_storage NULL
#define out_storage NULL
#endif
static double reference[CHANNELS] WORKSPACE;
static double tolerance[CHANNELS] WORKSPACE;
extern void run_mean_hw(float *, float *);

static uint32_t float_bits(float value) {
  union { float f; uint32_t u; } bits = {value};
  return bits.u;
}

static float x_value(int c, int h, int w, int trial) {
  int spatial = h * WIDTH + w;
  if (trial == 0) return spatial % 2 ? -0.0f : 0.0f;
  if (trial == 1) return (float)(c + 1) * (c % 2 ? -0.125f : 0.125f);
  if (trial == 2) return spatial == SPATIAL - 1 ? (float)(c + 1) * 0.25f : 0.0f;
  if (trial == 3) return (float)((c * 17 + h * 37 + w * 13) % 257 - 128) * 0.01f;
  if (trial == 4)
    return (spatial % 2 ? -32.0f : 32.0f) + (float)((spatial + c) % 11 - 5) * 0.0001f;
  if (trial == 5)
    return 1.0f + (float)(spatial % 31) * 0.0001f + (float)(c % 7) * 0.1f;
  return spatial == 0 ? (float)(c + 1) * -0.25f : 0.0f;
}

int launch(void) {
  GuardedBuffer x = {0}, out = {0};
  if (buffer_init(&x, COUNT, x_storage)) return report_check("mean_hw_c576_h7_w7", 1, 0);
  if (buffer_init(&out, CHANNELS, out_storage)) {
    buffer_free(&x); return report_check("mean_hw_c576_h7_w7", 1, 0);
  }
  unsigned errors = 0;
  double maximum = 0, maximum_ratio = 0, maximum_bound = 0;
  /* Conservative sum+division forward bound, with one extra FP32 rounding
   * step to cover double-oracle/tolerance evaluation. See MEAN_HW.md.
   * Masked zeros add no error. No assumption of a balanced reduction tree. */
  const double unit_roundoff = 0x1p-24;
  const double ku = (SPATIAL + 1) * unit_roundoff;
  const double gamma = ku / (1.0 - ku);
  for (int trial = 0; trial < TRIALS; ++trial) {
    for (int c = 0; c < CHANNELS; ++c) {
      out.data[c] = -9999.0f;
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w)
          x.data[(c * HEIGHT + h) * WIDTH + w] = x_value(c, h, w, trial);
    }
    /* Independent double accumulation, using explicit NCHW c/h/w loops.
     * Divide by HEIGHT*WIDTH, never by the padded Triton BLOCK. */
    for (int c = 0; c < CHANNELS; ++c) {
      double sum = 0, sum_abs = 0;
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w) {
          double value = x.data[(c * HEIGHT + h) * WIDTH + w];
          sum += value;
          sum_abs += value < 0 ? -value : value;
        }
      reference[c] = sum / SPATIAL;
      tolerance[c] = gamma * (sum_abs / SPATIAL) + 0x1p-149;
      if (tolerance[c] > maximum_bound) maximum_bound = tolerance[c];
    }
    run_mean_hw(x.data, out.data);
    for (int c = 0; c < CHANNELS; ++c) {
      if (!__builtin_isfinite(out.data[c])) {
        ++errors; maximum = __builtin_inf(); maximum_ratio = __builtin_inf();
      } else {
        double difference = (double)out.data[c] - reference[c];
        if (difference < 0) difference = -difference;
        errors += difference > tolerance[c];
        if (difference > maximum) maximum = difference;
        double ratio = difference / tolerance[c];
        if (ratio > maximum_ratio) maximum_ratio = ratio;
      }
      for (int h = 0; h < HEIGHT; ++h)
        for (int w = 0; w < WIDTH; ++w)
          errors += float_bits(x.data[(c * HEIGHT + h) * WIDTH + w]) !=
                    float_bits(x_value(c, h, w, trial));
    }
    errors += buffer_check(&x) + buffer_check(&out);
  }
  buffer_free(&x); buffer_free(&out);
#ifdef HOST_TEST
  printf("mean_hw metrics max_abs_error=%.17g max_error_over_bound=%.17g max_bound=%.17g\n",
         maximum, maximum_ratio, maximum_bound);
#endif
  return report_check("mean_hw_c576_h7_w7", errors, (float)maximum);
}

#ifdef HOST_TEST
int main(void) { return launch(); }
#endif
